{"name":"SequelizeConnectionRefusedError","parent":{"errno":-111,"code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":3306,"fatal":true},"original":{"errno":-111,"code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":3306,"fatal":true},"level":"\u001b[31merror\u001b[39m","message":"Unable to connect to the database: connect ECONNREFUSED 127.0.0.1:3306","stack":"SequelizeConnectionRefusedError: connect ECONNREFUSED 127.0.0.1:3306\n    at ConnectionManager.connect (/server/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:116:17)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async ConnectionManager._connect (/server/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:318:24)\n    at async /server/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:250:32\n    at async ConnectionManager.getConnection (/server/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:280:7)\n    at async /server/node_modules/sequelize/lib/sequelize.js:613:26\n    at async Sequelize.authenticate (/server/node_modules/sequelize/lib/sequelize.js:867:5)","timestamp":"2021-09-11T20:50:11.988Z"}
{"level":"\u001b[31merror\u001b[39m","message":"Cannot read property 'email' of undefined Cannot read property 'email' of undefined","stack":"TypeError: Cannot read property 'email' of undefined\n    at UserController.createUser (/server/server/controllers/user.controller.js:15:42)\n    at /server/server/routers/user.js:12:39\n    at Layer.handle [as handle_request] (/server/node_modules/express/lib/router/layer.js:95:5)\n    at next (/server/node_modules/express/lib/router/route.js:137:13)\n    at validateRequest (/server/server/schemas/validateRequest.js:13:5)\n    at userCreateSchema (/server/server/schemas/user.js:11:3)\n    at Layer.handle [as handle_request] (/server/node_modules/express/lib/router/layer.js:95:5)\n    at next (/server/node_modules/express/lib/router/route.js:137:13)\n    at Route.dispatch (/server/node_modules/express/lib/router/route.js:112:3)\n    at Layer.handle [as handle_request] (/server/node_modules/express/lib/router/layer.js:95:5)","timestamp":"2021-09-12T13:34:03.257Z"}
{"level":"\u001b[31merror\u001b[39m","message":"Cannot read property 'email' of undefined Cannot read property 'email' of undefined","stack":"TypeError: Cannot read property 'email' of undefined\n    at UserController.createUser (/server/server/controllers/user.controller.js:15:42)\n    at /server/server/routers/user.js:12:39\n    at Layer.handle [as handle_request] (/server/node_modules/express/lib/router/layer.js:95:5)\n    at next (/server/node_modules/express/lib/router/route.js:137:13)\n    at validateRequest (/server/server/schemas/validateRequest.js:13:5)\n    at userCreateSchema (/server/server/schemas/user.js:11:3)\n    at Layer.handle [as handle_request] (/server/node_modules/express/lib/router/layer.js:95:5)\n    at next (/server/node_modules/express/lib/router/route.js:137:13)\n    at Route.dispatch (/server/node_modules/express/lib/router/route.js:112:3)\n    at Layer.handle [as handle_request] (/server/node_modules/express/lib/router/layer.js:95:5)","timestamp":"2021-09-12T13:34:33.809Z"}
{"level":"\u001b[31merror\u001b[39m","message":"Cannot read property 'email' of undefined Cannot read property 'email' of undefined","stack":"TypeError: Cannot read property 'email' of undefined\n    at UserController.createUser (/server/server/controllers/user.controller.js:17:42)\n    at /server/server/routers/user.js:12:39\n    at Layer.handle [as handle_request] (/server/node_modules/express/lib/router/layer.js:95:5)\n    at next (/server/node_modules/express/lib/router/route.js:137:13)\n    at validateRequest (/server/server/schemas/validateRequest.js:13:5)\n    at userCreateSchema (/server/server/schemas/user.js:11:3)\n    at Layer.handle [as handle_request] (/server/node_modules/express/lib/router/layer.js:95:5)\n    at next (/server/node_modules/express/lib/router/route.js:137:13)\n    at Route.dispatch (/server/node_modules/express/lib/router/route.js:112:3)\n    at Layer.handle [as handle_request] (/server/node_modules/express/lib/router/layer.js:95:5)","timestamp":"2021-09-12T13:35:37.477Z"}
{"level":"\u001b[31merror\u001b[39m","message":"Cannot read property 'email' of undefined Cannot read property 'email' of undefined","stack":"TypeError: Cannot read property 'email' of undefined\n    at UserController.createUser (/server/server/controllers/user.controller.js:17:42)\n    at /server/server/routers/user.js:12:39\n    at Layer.handle [as handle_request] (/server/node_modules/express/lib/router/layer.js:95:5)\n    at next (/server/node_modules/express/lib/router/route.js:137:13)\n    at validateRequest (/server/server/schemas/validateRequest.js:12:5)\n    at userCreateSchema (/server/server/schemas/user.js:11:3)\n    at Layer.handle [as handle_request] (/server/node_modules/express/lib/router/layer.js:95:5)\n    at next (/server/node_modules/express/lib/router/route.js:137:13)\n    at Route.dispatch (/server/node_modules/express/lib/router/route.js:112:3)\n    at Layer.handle [as handle_request] (/server/node_modules/express/lib/router/layer.js:95:5)","timestamp":"2021-09-12T13:36:41.728Z"}
{"level":"\u001b[31merror\u001b[39m","message":"Cannot read property 'email' of undefined Cannot read property 'email' of undefined","stack":"TypeError: Cannot read property 'email' of undefined\n    at UserController.createUser (/server/server/controllers/user.controller.js:17:42)\n    at /server/server/routers/user.js:12:39\n    at Layer.handle [as handle_request] (/server/node_modules/express/lib/router/layer.js:95:5)\n    at next (/server/node_modules/express/lib/router/route.js:137:13)\n    at validateRequest (/server/server/schemas/validateRequest.js:12:5)\n    at userCreateSchema (/server/server/schemas/user.js:11:3)\n    at Layer.handle [as handle_request] (/server/node_modules/express/lib/router/layer.js:95:5)\n    at next (/server/node_modules/express/lib/router/route.js:137:13)\n    at Route.dispatch (/server/node_modules/express/lib/router/route.js:112:3)\n    at Layer.handle [as handle_request] (/server/node_modules/express/lib/router/layer.js:95:5)","timestamp":"2021-09-12T13:37:24.172Z"}
{"level":"\u001b[31merror\u001b[39m","message":"Cannot read property 'email' of undefined Cannot read property 'email' of undefined","stack":"TypeError: Cannot read property 'email' of undefined\n    at UserController.createUser (/server/server/controllers/user.controller.js:17:42)\n    at /server/server/routers/user.js:12:39\n    at Layer.handle [as handle_request] (/server/node_modules/express/lib/router/layer.js:95:5)\n    at next (/server/node_modules/express/lib/router/route.js:137:13)\n    at validateRequest (/server/server/schemas/validateRequest.js:14:10)\n    at userCreateSchema (/server/server/schemas/user.js:11:3)\n    at Layer.handle [as handle_request] (/server/node_modules/express/lib/router/layer.js:95:5)\n    at next (/server/node_modules/express/lib/router/route.js:137:13)\n    at Route.dispatch (/server/node_modules/express/lib/router/route.js:112:3)\n    at Layer.handle [as handle_request] (/server/node_modules/express/lib/router/layer.js:95:5)","timestamp":"2021-09-12T13:38:28.794Z"}
{"level":"\u001b[31merror\u001b[39m","message":"Cannot read property 'email' of undefined Cannot read property 'email' of undefined","stack":"TypeError: Cannot read property 'email' of undefined\n    at UserController.createUser (/server/server/controllers/user.controller.js:17:42)\n    at /server/server/routers/user.js:12:39\n    at Layer.handle [as handle_request] (/server/node_modules/express/lib/router/layer.js:95:5)\n    at next (/server/node_modules/express/lib/router/route.js:137:13)\n    at validateRequest (/server/server/schemas/validateRequest.js:14:10)\n    at userCreateSchema (/server/server/schemas/user.js:13:3)\n    at Layer.handle [as handle_request] (/server/node_modules/express/lib/router/layer.js:95:5)\n    at next (/server/node_modules/express/lib/router/route.js:137:13)\n    at Route.dispatch (/server/node_modules/express/lib/router/route.js:112:3)\n    at Layer.handle [as handle_request] (/server/node_modules/express/lib/router/layer.js:95:5)","timestamp":"2021-09-12T13:39:19.562Z"}
{"level":"\u001b[31merror\u001b[39m","message":"Cannot read property 'email' of undefined Cannot read property 'email' of undefined","stack":"TypeError: Cannot read property 'email' of undefined\n    at UserController.createUser (/server/server/controllers/user.controller.js:17:42)\n    at /server/server/routers/user.js:12:39\n    at Layer.handle [as handle_request] (/server/node_modules/express/lib/router/layer.js:95:5)\n    at next (/server/node_modules/express/lib/router/route.js:137:13)\n    at validateRequest (/server/server/schemas/validateRequest.js:14:10)\n    at userCreateSchema (/server/server/schemas/user.js:13:3)\n    at Layer.handle [as handle_request] (/server/node_modules/express/lib/router/layer.js:95:5)\n    at next (/server/node_modules/express/lib/router/route.js:137:13)\n    at Route.dispatch (/server/node_modules/express/lib/router/route.js:112:3)\n    at Layer.handle [as handle_request] (/server/node_modules/express/lib/router/layer.js:95:5)","timestamp":"2021-09-12T13:44:49.135Z"}
{"level":"\u001b[31merror\u001b[39m","message":"Cannot read property 'email' of undefined Cannot read property 'email' of undefined","stack":"TypeError: Cannot read property 'email' of undefined\n    at UserController.createUser (/server/server/controllers/user.controller.js:17:42)\n    at /server/server/routers/user.js:12:39\n    at Layer.handle [as handle_request] (/server/node_modules/express/lib/router/layer.js:95:5)\n    at next (/server/node_modules/express/lib/router/route.js:137:13)\n    at Route.dispatch (/server/node_modules/express/lib/router/route.js:112:3)\n    at Layer.handle [as handle_request] (/server/node_modules/express/lib/router/layer.js:95:5)\n    at /server/node_modules/express/lib/router/index.js:281:22\n    at Function.process_params (/server/node_modules/express/lib/router/index.js:335:12)\n    at next (/server/node_modules/express/lib/router/index.js:275:10)\n    at Function.handle (/server/node_modules/express/lib/router/index.js:174:3)","timestamp":"2021-09-12T13:45:30.010Z"}
{"level":"\u001b[31merror\u001b[39m","message":"Support for `{where: 'raw query'}` has been removed. Support for `{where: 'raw query'}` has been removed.","stack":"Error: Support for `{where: 'raw query'}` has been removed.\n    at MySQLQueryGenerator.whereItemsQuery (/server/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2247:13)\n    at MySQLQueryGenerator.getWhereConditions (/server/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2698:19)\n    at MySQLQueryGenerator.selectQuery (/server/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1325:28)\n    at MySQLQueryInterface.select (/server/node_modules/sequelize/lib/dialects/abstract/query-interface.js:954:27)\n    at Function.findAll (/server/node_modules/sequelize/lib/model.js:1753:47)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async Function.findOne (/server/node_modules/sequelize/lib/model.js:1917:12)\n    at async UserAdapter.get (/server/server/adapters/mysql_database/BaseAdapter.js:38:24)\n    at async UserController.get (/server/server/controllers/Controller.js:41:24)\n    at async UserController.createUser (/server/server/controllers/user.controller.js:17:18)","timestamp":"2021-09-12T13:49:48.368Z"}
{"level":"\u001b[31merror\u001b[39m","message":"Support for `{where: 'raw query'}` has been removed. Support for `{where: 'raw query'}` has been removed.","stack":"Error: Support for `{where: 'raw query'}` has been removed.\n    at MySQLQueryGenerator.whereItemsQuery (/server/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2247:13)\n    at MySQLQueryGenerator.getWhereConditions (/server/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2698:19)\n    at MySQLQueryGenerator.selectQuery (/server/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1325:28)\n    at MySQLQueryInterface.select (/server/node_modules/sequelize/lib/dialects/abstract/query-interface.js:954:27)\n    at Function.findAll (/server/node_modules/sequelize/lib/model.js:1753:47)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async Function.findOne (/server/node_modules/sequelize/lib/model.js:1917:12)\n    at async UserAdapter.get (/server/server/adapters/mysql_database/BaseAdapter.js:38:24)\n    at async UserController.get (/server/server/controllers/Controller.js:41:24)\n    at async UserController.createUser (/server/server/controllers/user.controller.js:17:18)","timestamp":"2021-09-12T13:49:48.369Z"}
{"level":"\u001b[31merror\u001b[39m","message":"Support for `{where: 'raw query'}` has been removed. Support for `{where: 'raw query'}` has been removed.","stack":"Error: Support for `{where: 'raw query'}` has been removed.\n    at MySQLQueryGenerator.whereItemsQuery (/server/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2247:13)\n    at MySQLQueryGenerator.getWhereConditions (/server/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2698:19)\n    at MySQLQueryGenerator.selectQuery (/server/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1325:28)\n    at MySQLQueryInterface.select (/server/node_modules/sequelize/lib/dialects/abstract/query-interface.js:954:27)\n    at Function.findAll (/server/node_modules/sequelize/lib/model.js:1753:47)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async Function.findOne (/server/node_modules/sequelize/lib/model.js:1917:12)\n    at async UserAdapter.get (/server/server/adapters/mysql_database/BaseAdapter.js:38:24)\n    at async UserController.get (/server/server/controllers/Controller.js:41:24)\n    at async UserController.createUser (/server/server/controllers/user.controller.js:17:18)","timestamp":"2021-09-12T13:49:48.370Z"}
{"level":"\u001b[31merror\u001b[39m","message":"Support for `{where: 'raw query'}` has been removed. Support for `{where: 'raw query'}` has been removed.","stack":"Error: Support for `{where: 'raw query'}` has been removed.\n    at MySQLQueryGenerator.whereItemsQuery (/server/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2247:13)\n    at MySQLQueryGenerator.getWhereConditions (/server/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2698:19)\n    at MySQLQueryGenerator.selectQuery (/server/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1325:28)\n    at MySQLQueryInterface.select (/server/node_modules/sequelize/lib/dialects/abstract/query-interface.js:954:27)\n    at Function.findAll (/server/node_modules/sequelize/lib/model.js:1753:47)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async Function.findOne (/server/node_modules/sequelize/lib/model.js:1917:12)\n    at async UserAdapter.get (/server/server/adapters/mysql_database/BaseAdapter.js:38:24)\n    at async UserController.get (/server/server/controllers/Controller.js:41:24)\n    at async UserController.createUser (/server/server/controllers/user.controller.js:15:18)","timestamp":"2021-09-12T13:52:53.330Z"}
{"level":"\u001b[31merror\u001b[39m","message":"Support for `{where: 'raw query'}` has been removed. Support for `{where: 'raw query'}` has been removed.","stack":"Error: Support for `{where: 'raw query'}` has been removed.\n    at MySQLQueryGenerator.whereItemsQuery (/server/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2247:13)\n    at MySQLQueryGenerator.getWhereConditions (/server/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2698:19)\n    at MySQLQueryGenerator.selectQuery (/server/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1325:28)\n    at MySQLQueryInterface.select (/server/node_modules/sequelize/lib/dialects/abstract/query-interface.js:954:27)\n    at Function.findAll (/server/node_modules/sequelize/lib/model.js:1753:47)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async Function.findOne (/server/node_modules/sequelize/lib/model.js:1917:12)\n    at async UserAdapter.get (/server/server/adapters/mysql_database/BaseAdapter.js:38:24)\n    at async UserController.get (/server/server/controllers/Controller.js:41:24)\n    at async UserController.createUser (/server/server/controllers/user.controller.js:15:18)","timestamp":"2021-09-12T13:52:53.331Z"}
{"level":"\u001b[31merror\u001b[39m","message":"Support for `{where: 'raw query'}` has been removed. Support for `{where: 'raw query'}` has been removed.","stack":"Error: Support for `{where: 'raw query'}` has been removed.\n    at MySQLQueryGenerator.whereItemsQuery (/server/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2247:13)\n    at MySQLQueryGenerator.getWhereConditions (/server/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2698:19)\n    at MySQLQueryGenerator.selectQuery (/server/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1325:28)\n    at MySQLQueryInterface.select (/server/node_modules/sequelize/lib/dialects/abstract/query-interface.js:954:27)\n    at Function.findAll (/server/node_modules/sequelize/lib/model.js:1753:47)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async Function.findOne (/server/node_modules/sequelize/lib/model.js:1917:12)\n    at async UserAdapter.get (/server/server/adapters/mysql_database/BaseAdapter.js:38:24)\n    at async UserController.get (/server/server/controllers/Controller.js:41:24)\n    at async UserController.createUser (/server/server/controllers/user.controller.js:15:18)","timestamp":"2021-09-12T13:52:53.331Z"}
{"level":"\u001b[31merror\u001b[39m","message":"(intermediate value).get is not a function (intermediate value).get is not a function","stack":"TypeError: (intermediate value).get is not a function\n    at UserAdapter.getOne (/server/server/adapters/mysql_database/user.adapter.js:33:32)\n    at UserController.getOne (/server/server/controllers/Controller.js:41:43)\n    at UserController.createUser (/server/server/controllers/user.controller.js:15:30)\n    at /server/server/routers/user.js:12:39\n    at Layer.handle [as handle_request] (/server/node_modules/express/lib/router/layer.js:95:5)\n    at next (/server/node_modules/express/lib/router/route.js:137:13)\n    at validateRequest (/server/server/schemas/validateRequest.js:14:10)\n    at userCreateSchema (/server/server/schemas/user.js:11:3)\n    at Layer.handle [as handle_request] (/server/node_modules/express/lib/router/layer.js:95:5)\n    at next (/server/node_modules/express/lib/router/route.js:137:13)","timestamp":"2021-09-12T14:03:51.073Z"}
{"level":"\u001b[31merror\u001b[39m","message":"(intermediate value).get is not a function (intermediate value).get is not a function","stack":"TypeError: (intermediate value).get is not a function\n    at UserAdapter.getOne (/server/server/adapters/mysql_database/user.adapter.js:33:32)\n    at UserController.getOne (/server/server/controllers/Controller.js:41:43)\n    at UserController.createUser (/server/server/controllers/user.controller.js:15:30)\n    at /server/server/routers/user.js:12:39\n    at Layer.handle [as handle_request] (/server/node_modules/express/lib/router/layer.js:95:5)\n    at next (/server/node_modules/express/lib/router/route.js:137:13)\n    at validateRequest (/server/server/schemas/validateRequest.js:14:10)\n    at userCreateSchema (/server/server/schemas/user.js:11:3)\n    at Layer.handle [as handle_request] (/server/node_modules/express/lib/router/layer.js:95:5)\n    at next (/server/node_modules/express/lib/router/route.js:137:13)","timestamp":"2021-09-12T14:03:51.075Z"}
{"level":"\u001b[31merror\u001b[39m","message":"(intermediate value).get is not a function (intermediate value).get is not a function","stack":"TypeError: (intermediate value).get is not a function\n    at UserAdapter.getOne (/server/server/adapters/mysql_database/user.adapter.js:33:32)\n    at UserController.getOne (/server/server/controllers/Controller.js:41:43)\n    at UserController.createUser (/server/server/controllers/user.controller.js:15:30)\n    at /server/server/routers/user.js:12:39\n    at Layer.handle [as handle_request] (/server/node_modules/express/lib/router/layer.js:95:5)\n    at next (/server/node_modules/express/lib/router/route.js:137:13)\n    at validateRequest (/server/server/schemas/validateRequest.js:14:10)\n    at userCreateSchema (/server/server/schemas/user.js:11:3)\n    at Layer.handle [as handle_request] (/server/node_modules/express/lib/router/layer.js:95:5)\n    at next (/server/node_modules/express/lib/router/route.js:137:13)","timestamp":"2021-09-12T14:03:51.076Z"}
{"level":"\u001b[31merror\u001b[39m","message":"(intermediate value).get is not a function (intermediate value).get is not a function","stack":"TypeError: (intermediate value).get is not a function\n    at UserAdapter.getOne (/server/server/adapters/mysql_database/user.adapter.js:33:32)\n    at UserController.getOne (/server/server/controllers/Controller.js:41:43)\n    at UserController.createUser (/server/server/controllers/user.controller.js:15:30)\n    at /server/server/routers/user.js:12:39\n    at Layer.handle [as handle_request] (/server/node_modules/express/lib/router/layer.js:95:5)\n    at next (/server/node_modules/express/lib/router/route.js:137:13)\n    at validateRequest (/server/server/schemas/validateRequest.js:14:10)\n    at userCreateSchema (/server/server/schemas/user.js:11:3)\n    at Layer.handle [as handle_request] (/server/node_modules/express/lib/router/layer.js:95:5)\n    at next (/server/node_modules/express/lib/router/route.js:137:13)","timestamp":"2021-09-12T14:04:32.128Z"}
{"level":"\u001b[31merror\u001b[39m","message":"(intermediate value).get is not a function (intermediate value).get is not a function","stack":"TypeError: (intermediate value).get is not a function\n    at UserAdapter.getOne (/server/server/adapters/mysql_database/user.adapter.js:33:32)\n    at UserController.getOne (/server/server/controllers/Controller.js:41:43)\n    at UserController.createUser (/server/server/controllers/user.controller.js:15:30)\n    at /server/server/routers/user.js:12:39\n    at Layer.handle [as handle_request] (/server/node_modules/express/lib/router/layer.js:95:5)\n    at next (/server/node_modules/express/lib/router/route.js:137:13)\n    at validateRequest (/server/server/schemas/validateRequest.js:14:10)\n    at userCreateSchema (/server/server/schemas/user.js:11:3)\n    at Layer.handle [as handle_request] (/server/node_modules/express/lib/router/layer.js:95:5)\n    at next (/server/node_modules/express/lib/router/route.js:137:13)","timestamp":"2021-09-12T14:04:32.130Z"}
{"level":"\u001b[31merror\u001b[39m","message":"(intermediate value).get is not a function (intermediate value).get is not a function","stack":"TypeError: (intermediate value).get is not a function\n    at UserAdapter.getOne (/server/server/adapters/mysql_database/user.adapter.js:33:32)\n    at UserController.getOne (/server/server/controllers/Controller.js:41:43)\n    at UserController.createUser (/server/server/controllers/user.controller.js:15:30)\n    at /server/server/routers/user.js:12:39\n    at Layer.handle [as handle_request] (/server/node_modules/express/lib/router/layer.js:95:5)\n    at next (/server/node_modules/express/lib/router/route.js:137:13)\n    at validateRequest (/server/server/schemas/validateRequest.js:14:10)\n    at userCreateSchema (/server/server/schemas/user.js:11:3)\n    at Layer.handle [as handle_request] (/server/node_modules/express/lib/router/layer.js:95:5)\n    at next (/server/node_modules/express/lib/router/route.js:137:13)","timestamp":"2021-09-12T14:04:32.130Z"}
{"name":"SequelizeDatabaseError","parent":{"code":"ER_NO_SUCH_TABLE","errno":1146,"sqlState":"42S02","sqlMessage":"Table 'test_db.users' doesn't exist","sql":"SELECT `id`, `firstname`, `lastname`, `email`, `password`, `createdAt`, `updatedAt` FROM `users` AS `user` WHERE `user`.`email` = 'mosta1996@hotmail.com' LIMIT 1;"},"original":{"code":"ER_NO_SUCH_TABLE","errno":1146,"sqlState":"42S02","sqlMessage":"Table 'test_db.users' doesn't exist","sql":"SELECT `id`, `firstname`, `lastname`, `email`, `password`, `createdAt`, `updatedAt` FROM `users` AS `user` WHERE `user`.`email` = 'mosta1996@hotmail.com' LIMIT 1;"},"sql":"SELECT `id`, `firstname`, `lastname`, `email`, `password`, `createdAt`, `updatedAt` FROM `users` AS `user` WHERE `user`.`email` = 'mosta1996@hotmail.com' LIMIT 1;","level":"\u001b[31merror\u001b[39m","message":"Table 'test_db.users' doesn't exist Table 'test_db.users' doesn't exist","stack":"SequelizeDatabaseError: Table 'test_db.users' doesn't exist\n    at Query.formatError (/server/node_modules/sequelize/lib/dialects/mysql/query.js:265:16)\n    at Query.run (/server/node_modules/sequelize/lib/dialects/mysql/query.js:77:18)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async /server/node_modules/sequelize/lib/sequelize.js:619:16\n    at async MySQLQueryInterface.select (/server/node_modules/sequelize/lib/dialects/abstract/query-interface.js:953:12)\n    at async Function.findAll (/server/node_modules/sequelize/lib/model.js:1753:21)\n    at async Function.findOne (/server/node_modules/sequelize/lib/model.js:1917:12)\n    at async UserAdapter.getOne (/server/server/adapters/mysql_database/BaseAdapter.js:38:24)\n    at async UserAdapter.getOne (/server/server/adapters/mysql_database/user.adapter.js:33:20)\n    at async UserController.getOne (/server/server/controllers/Controller.js:41:24)","timestamp":"2021-09-12T14:05:17.405Z"}
{"name":"SequelizeDatabaseError","parent":{"code":"ER_NO_SUCH_TABLE","errno":1146,"sqlState":"42S02","sqlMessage":"Table 'test_db.users' doesn't exist","sql":"SELECT `id`, `firstname`, `lastname`, `email`, `password`, `createdAt`, `updatedAt` FROM `users` AS `user` WHERE `user`.`email` = 'mosta1996@hotmail.com' LIMIT 1;"},"original":{"code":"ER_NO_SUCH_TABLE","errno":1146,"sqlState":"42S02","sqlMessage":"Table 'test_db.users' doesn't exist","sql":"SELECT `id`, `firstname`, `lastname`, `email`, `password`, `createdAt`, `updatedAt` FROM `users` AS `user` WHERE `user`.`email` = 'mosta1996@hotmail.com' LIMIT 1;"},"sql":"SELECT `id`, `firstname`, `lastname`, `email`, `password`, `createdAt`, `updatedAt` FROM `users` AS `user` WHERE `user`.`email` = 'mosta1996@hotmail.com' LIMIT 1;","level":"\u001b[31merror\u001b[39m","message":"Table 'test_db.users' doesn't exist Table 'test_db.users' doesn't exist","stack":"SequelizeDatabaseError: Table 'test_db.users' doesn't exist\n    at Query.formatError (/server/node_modules/sequelize/lib/dialects/mysql/query.js:265:16)\n    at Query.run (/server/node_modules/sequelize/lib/dialects/mysql/query.js:77:18)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async /server/node_modules/sequelize/lib/sequelize.js:619:16\n    at async MySQLQueryInterface.select (/server/node_modules/sequelize/lib/dialects/abstract/query-interface.js:953:12)\n    at async Function.findAll (/server/node_modules/sequelize/lib/model.js:1753:21)\n    at async Function.findOne (/server/node_modules/sequelize/lib/model.js:1917:12)\n    at async UserAdapter.getOne (/server/server/adapters/mysql_database/BaseAdapter.js:38:24)\n    at async UserAdapter.getOne (/server/server/adapters/mysql_database/user.adapter.js:33:20)\n    at async UserController.getOne (/server/server/controllers/Controller.js:41:24)","timestamp":"2021-09-12T14:05:17.406Z"}
{"name":"SequelizeDatabaseError","parent":{"code":"ER_NO_SUCH_TABLE","errno":1146,"sqlState":"42S02","sqlMessage":"Table 'test_db.users' doesn't exist","sql":"SELECT `id`, `firstname`, `lastname`, `email`, `password`, `createdAt`, `updatedAt` FROM `users` AS `user` WHERE `user`.`email` = 'mosta1996@hotmail.com' LIMIT 1;"},"original":{"code":"ER_NO_SUCH_TABLE","errno":1146,"sqlState":"42S02","sqlMessage":"Table 'test_db.users' doesn't exist","sql":"SELECT `id`, `firstname`, `lastname`, `email`, `password`, `createdAt`, `updatedAt` FROM `users` AS `user` WHERE `user`.`email` = 'mosta1996@hotmail.com' LIMIT 1;"},"sql":"SELECT `id`, `firstname`, `lastname`, `email`, `password`, `createdAt`, `updatedAt` FROM `users` AS `user` WHERE `user`.`email` = 'mosta1996@hotmail.com' LIMIT 1;","level":"\u001b[31merror\u001b[39m","message":"Table 'test_db.users' doesn't exist Table 'test_db.users' doesn't exist","stack":"SequelizeDatabaseError: Table 'test_db.users' doesn't exist\n    at Query.formatError (/server/node_modules/sequelize/lib/dialects/mysql/query.js:265:16)\n    at Query.run (/server/node_modules/sequelize/lib/dialects/mysql/query.js:77:18)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async /server/node_modules/sequelize/lib/sequelize.js:619:16\n    at async MySQLQueryInterface.select (/server/node_modules/sequelize/lib/dialects/abstract/query-interface.js:953:12)\n    at async Function.findAll (/server/node_modules/sequelize/lib/model.js:1753:21)\n    at async Function.findOne (/server/node_modules/sequelize/lib/model.js:1917:12)\n    at async UserAdapter.getOne (/server/server/adapters/mysql_database/BaseAdapter.js:38:24)\n    at async UserAdapter.getOne (/server/server/adapters/mysql_database/user.adapter.js:33:20)\n    at async UserController.getOne (/server/server/controllers/Controller.js:41:24)","timestamp":"2021-09-12T14:05:17.406Z"}
{"name":"SequelizeDatabaseError","parent":{"code":"ER_NO_SUCH_TABLE","errno":1146,"sqlState":"42S02","sqlMessage":"Table 'test_db.users' doesn't exist","sql":"SELECT `id`, `firstname`, `lastname`, `email`, `password`, `createdAt`, `updatedAt` FROM `users` AS `user` WHERE `user`.`email` = 'mosta1996@hotmail.com' LIMIT 1;"},"original":{"code":"ER_NO_SUCH_TABLE","errno":1146,"sqlState":"42S02","sqlMessage":"Table 'test_db.users' doesn't exist","sql":"SELECT `id`, `firstname`, `lastname`, `email`, `password`, `createdAt`, `updatedAt` FROM `users` AS `user` WHERE `user`.`email` = 'mosta1996@hotmail.com' LIMIT 1;"},"sql":"SELECT `id`, `firstname`, `lastname`, `email`, `password`, `createdAt`, `updatedAt` FROM `users` AS `user` WHERE `user`.`email` = 'mosta1996@hotmail.com' LIMIT 1;","level":"\u001b[31merror\u001b[39m","message":"Table 'test_db.users' doesn't exist Table 'test_db.users' doesn't exist","stack":"SequelizeDatabaseError: Table 'test_db.users' doesn't exist\n    at Query.formatError (/server/node_modules/sequelize/lib/dialects/mysql/query.js:265:16)\n    at Query.run (/server/node_modules/sequelize/lib/dialects/mysql/query.js:77:18)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async /server/node_modules/sequelize/lib/sequelize.js:619:16\n    at async MySQLQueryInterface.select (/server/node_modules/sequelize/lib/dialects/abstract/query-interface.js:953:12)\n    at async Function.findAll (/server/node_modules/sequelize/lib/model.js:1753:21)\n    at async Function.findOne (/server/node_modules/sequelize/lib/model.js:1917:12)\n    at async UserAdapter.getOne (/server/server/adapters/mysql_database/BaseAdapter.js:38:24)\n    at async UserAdapter.getOne (/server/server/adapters/mysql_database/user.adapter.js:33:20)\n    at async UserController.getOne (/server/server/controllers/Controller.js:41:24)","timestamp":"2021-09-12T14:05:17.406Z"}
{"name":"SequelizeDatabaseError","parent":{"code":"ER_NO_SUCH_TABLE","errno":1146,"sqlState":"42S02","sqlMessage":"Table 'test_db.users' doesn't exist","sql":"SELECT `id`, `firstname`, `lastname`, `email`, `password`, `createdAt`, `updatedAt` FROM `users` AS `user` WHERE `user`.`email` = 'mosta1996@hotmail.com' LIMIT 1;"},"original":{"code":"ER_NO_SUCH_TABLE","errno":1146,"sqlState":"42S02","sqlMessage":"Table 'test_db.users' doesn't exist","sql":"SELECT `id`, `firstname`, `lastname`, `email`, `password`, `createdAt`, `updatedAt` FROM `users` AS `user` WHERE `user`.`email` = 'mosta1996@hotmail.com' LIMIT 1;"},"sql":"SELECT `id`, `firstname`, `lastname`, `email`, `password`, `createdAt`, `updatedAt` FROM `users` AS `user` WHERE `user`.`email` = 'mosta1996@hotmail.com' LIMIT 1;","level":"\u001b[31merror\u001b[39m","message":"Table 'test_db.users' doesn't exist Table 'test_db.users' doesn't exist","stack":"SequelizeDatabaseError: Table 'test_db.users' doesn't exist\n    at Query.formatError (/server/node_modules/sequelize/lib/dialects/mysql/query.js:265:16)\n    at Query.run (/server/node_modules/sequelize/lib/dialects/mysql/query.js:77:18)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async /server/node_modules/sequelize/lib/sequelize.js:619:16\n    at async MySQLQueryInterface.select (/server/node_modules/sequelize/lib/dialects/abstract/query-interface.js:953:12)\n    at async Function.findAll (/server/node_modules/sequelize/lib/model.js:1753:21)\n    at async Function.findOne (/server/node_modules/sequelize/lib/model.js:1917:12)\n    at async UserAdapter.getOne (/server/server/adapters/mysql_database/BaseAdapter.js:38:24)\n    at async UserAdapter.getOne (/server/server/adapters/mysql_database/user.adapter.js:33:20)\n    at async UserController.getOne (/server/server/controllers/Controller.js:41:24)","timestamp":"2021-09-12T18:27:35.429Z"}
{"name":"SequelizeDatabaseError","parent":{"code":"ER_NO_SUCH_TABLE","errno":1146,"sqlState":"42S02","sqlMessage":"Table 'test_db.users' doesn't exist","sql":"SELECT `id`, `firstname`, `lastname`, `email`, `password`, `createdAt`, `updatedAt` FROM `users` AS `user` WHERE `user`.`email` = 'mosta1996@hotmail.com' LIMIT 1;"},"original":{"code":"ER_NO_SUCH_TABLE","errno":1146,"sqlState":"42S02","sqlMessage":"Table 'test_db.users' doesn't exist","sql":"SELECT `id`, `firstname`, `lastname`, `email`, `password`, `createdAt`, `updatedAt` FROM `users` AS `user` WHERE `user`.`email` = 'mosta1996@hotmail.com' LIMIT 1;"},"sql":"SELECT `id`, `firstname`, `lastname`, `email`, `password`, `createdAt`, `updatedAt` FROM `users` AS `user` WHERE `user`.`email` = 'mosta1996@hotmail.com' LIMIT 1;","level":"\u001b[31merror\u001b[39m","message":"Table 'test_db.users' doesn't exist Table 'test_db.users' doesn't exist","stack":"SequelizeDatabaseError: Table 'test_db.users' doesn't exist\n    at Query.formatError (/server/node_modules/sequelize/lib/dialects/mysql/query.js:265:16)\n    at Query.run (/server/node_modules/sequelize/lib/dialects/mysql/query.js:77:18)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async /server/node_modules/sequelize/lib/sequelize.js:619:16\n    at async MySQLQueryInterface.select (/server/node_modules/sequelize/lib/dialects/abstract/query-interface.js:953:12)\n    at async Function.findAll (/server/node_modules/sequelize/lib/model.js:1753:21)\n    at async Function.findOne (/server/node_modules/sequelize/lib/model.js:1917:12)\n    at async UserAdapter.getOne (/server/server/adapters/mysql_database/BaseAdapter.js:38:24)\n    at async UserAdapter.getOne (/server/server/adapters/mysql_database/user.adapter.js:33:20)\n    at async UserController.getOne (/server/server/controllers/Controller.js:41:24)","timestamp":"2021-09-12T18:27:35.430Z"}
{"name":"SequelizeDatabaseError","parent":{"code":"ER_NO_SUCH_TABLE","errno":1146,"sqlState":"42S02","sqlMessage":"Table 'test_db.users' doesn't exist","sql":"SELECT `id`, `firstname`, `lastname`, `email`, `password`, `createdAt`, `updatedAt` FROM `users` AS `user` WHERE `user`.`email` = 'mosta1996@hotmail.com' LIMIT 1;"},"original":{"code":"ER_NO_SUCH_TABLE","errno":1146,"sqlState":"42S02","sqlMessage":"Table 'test_db.users' doesn't exist","sql":"SELECT `id`, `firstname`, `lastname`, `email`, `password`, `createdAt`, `updatedAt` FROM `users` AS `user` WHERE `user`.`email` = 'mosta1996@hotmail.com' LIMIT 1;"},"sql":"SELECT `id`, `firstname`, `lastname`, `email`, `password`, `createdAt`, `updatedAt` FROM `users` AS `user` WHERE `user`.`email` = 'mosta1996@hotmail.com' LIMIT 1;","level":"\u001b[31merror\u001b[39m","message":"Table 'test_db.users' doesn't exist Table 'test_db.users' doesn't exist","stack":"SequelizeDatabaseError: Table 'test_db.users' doesn't exist\n    at Query.formatError (/server/node_modules/sequelize/lib/dialects/mysql/query.js:265:16)\n    at Query.run (/server/node_modules/sequelize/lib/dialects/mysql/query.js:77:18)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async /server/node_modules/sequelize/lib/sequelize.js:619:16\n    at async MySQLQueryInterface.select (/server/node_modules/sequelize/lib/dialects/abstract/query-interface.js:953:12)\n    at async Function.findAll (/server/node_modules/sequelize/lib/model.js:1753:21)\n    at async Function.findOne (/server/node_modules/sequelize/lib/model.js:1917:12)\n    at async UserAdapter.getOne (/server/server/adapters/mysql_database/BaseAdapter.js:38:24)\n    at async UserAdapter.getOne (/server/server/adapters/mysql_database/user.adapter.js:33:20)\n    at async UserController.getOne (/server/server/controllers/Controller.js:41:24)","timestamp":"2021-09-12T18:27:35.431Z"}
{"name":"SequelizeDatabaseError","parent":{"code":"ER_NO_SUCH_TABLE","errno":1146,"sqlState":"42S02","sqlMessage":"Table 'test_db.users' doesn't exist","sql":"SELECT `id`, `firstname`, `lastname`, `email`, `password`, `createdAt`, `updatedAt` FROM `users` AS `user` WHERE `user`.`email` = 'mosta1996@hotmail.com' LIMIT 1;"},"original":{"code":"ER_NO_SUCH_TABLE","errno":1146,"sqlState":"42S02","sqlMessage":"Table 'test_db.users' doesn't exist","sql":"SELECT `id`, `firstname`, `lastname`, `email`, `password`, `createdAt`, `updatedAt` FROM `users` AS `user` WHERE `user`.`email` = 'mosta1996@hotmail.com' LIMIT 1;"},"sql":"SELECT `id`, `firstname`, `lastname`, `email`, `password`, `createdAt`, `updatedAt` FROM `users` AS `user` WHERE `user`.`email` = 'mosta1996@hotmail.com' LIMIT 1;","level":"\u001b[31merror\u001b[39m","message":"Table 'test_db.users' doesn't exist Table 'test_db.users' doesn't exist","stack":"SequelizeDatabaseError: Table 'test_db.users' doesn't exist\n    at Query.formatError (/server/node_modules/sequelize/lib/dialects/mysql/query.js:265:16)\n    at Query.run (/server/node_modules/sequelize/lib/dialects/mysql/query.js:77:18)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async /server/node_modules/sequelize/lib/sequelize.js:619:16\n    at async MySQLQueryInterface.select (/server/node_modules/sequelize/lib/dialects/abstract/query-interface.js:953:12)\n    at async Function.findAll (/server/node_modules/sequelize/lib/model.js:1753:21)\n    at async Function.findOne (/server/node_modules/sequelize/lib/model.js:1917:12)\n    at async UserAdapter.getOne (/server/server/adapters/mysql_database/BaseAdapter.js:38:24)\n    at async UserAdapter.getOne (/server/server/adapters/mysql_database/user.adapter.js:33:20)\n    at async UserController.getOne (/server/server/controllers/Controller.js:41:24)","timestamp":"2021-09-12T18:27:35.431Z"}
{"name":"SequelizeDatabaseError","parent":{"code":"ER_NO_SUCH_TABLE","errno":1146,"sqlState":"42S02","sqlMessage":"Table 'test_db.users' doesn't exist","sql":"SELECT `id`, `firstname`, `lastname`, `email`, `password`, `createdAt`, `updatedAt` FROM `users` AS `user` WHERE `user`.`email` = 'mosta1996@hotmail.com' LIMIT 1;"},"original":{"code":"ER_NO_SUCH_TABLE","errno":1146,"sqlState":"42S02","sqlMessage":"Table 'test_db.users' doesn't exist","sql":"SELECT `id`, `firstname`, `lastname`, `email`, `password`, `createdAt`, `updatedAt` FROM `users` AS `user` WHERE `user`.`email` = 'mosta1996@hotmail.com' LIMIT 1;"},"sql":"SELECT `id`, `firstname`, `lastname`, `email`, `password`, `createdAt`, `updatedAt` FROM `users` AS `user` WHERE `user`.`email` = 'mosta1996@hotmail.com' LIMIT 1;","level":"\u001b[31merror\u001b[39m","message":"Table 'test_db.users' doesn't exist Table 'test_db.users' doesn't exist","stack":"SequelizeDatabaseError: Table 'test_db.users' doesn't exist\n    at Query.formatError (/server/node_modules/sequelize/lib/dialects/mysql/query.js:265:16)\n    at Query.run (/server/node_modules/sequelize/lib/dialects/mysql/query.js:77:18)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async /server/node_modules/sequelize/lib/sequelize.js:619:16\n    at async MySQLQueryInterface.select (/server/node_modules/sequelize/lib/dialects/abstract/query-interface.js:953:12)\n    at async Function.findAll (/server/node_modules/sequelize/lib/model.js:1753:21)\n    at async Function.findOne (/server/node_modules/sequelize/lib/model.js:1917:12)\n    at async UserAdapter.getOne (/server/server/adapters/mysql_database/BaseAdapter.js:38:24)\n    at async UserAdapter.getOne (/server/server/adapters/mysql_database/user.adapter.js:33:20)\n    at async UserController.getOne (/server/server/controllers/Controller.js:41:24)","timestamp":"2021-09-12T18:28:07.677Z"}
{"name":"SequelizeDatabaseError","parent":{"code":"ER_NO_SUCH_TABLE","errno":1146,"sqlState":"42S02","sqlMessage":"Table 'test_db.users' doesn't exist","sql":"SELECT `id`, `firstname`, `lastname`, `email`, `password`, `createdAt`, `updatedAt` FROM `users` AS `user` WHERE `user`.`email` = 'mosta1996@hotmail.com' LIMIT 1;"},"original":{"code":"ER_NO_SUCH_TABLE","errno":1146,"sqlState":"42S02","sqlMessage":"Table 'test_db.users' doesn't exist","sql":"SELECT `id`, `firstname`, `lastname`, `email`, `password`, `createdAt`, `updatedAt` FROM `users` AS `user` WHERE `user`.`email` = 'mosta1996@hotmail.com' LIMIT 1;"},"sql":"SELECT `id`, `firstname`, `lastname`, `email`, `password`, `createdAt`, `updatedAt` FROM `users` AS `user` WHERE `user`.`email` = 'mosta1996@hotmail.com' LIMIT 1;","level":"\u001b[31merror\u001b[39m","message":"Table 'test_db.users' doesn't exist Table 'test_db.users' doesn't exist","stack":"SequelizeDatabaseError: Table 'test_db.users' doesn't exist\n    at Query.formatError (/server/node_modules/sequelize/lib/dialects/mysql/query.js:265:16)\n    at Query.run (/server/node_modules/sequelize/lib/dialects/mysql/query.js:77:18)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async /server/node_modules/sequelize/lib/sequelize.js:619:16\n    at async MySQLQueryInterface.select (/server/node_modules/sequelize/lib/dialects/abstract/query-interface.js:953:12)\n    at async Function.findAll (/server/node_modules/sequelize/lib/model.js:1753:21)\n    at async Function.findOne (/server/node_modules/sequelize/lib/model.js:1917:12)\n    at async UserAdapter.getOne (/server/server/adapters/mysql_database/BaseAdapter.js:38:24)\n    at async UserAdapter.getOne (/server/server/adapters/mysql_database/user.adapter.js:33:20)\n    at async UserController.getOne (/server/server/controllers/Controller.js:41:24)","timestamp":"2021-09-12T18:28:07.678Z"}
{"name":"SequelizeDatabaseError","parent":{"code":"ER_NO_SUCH_TABLE","errno":1146,"sqlState":"42S02","sqlMessage":"Table 'test_db.users' doesn't exist","sql":"SELECT `id`, `firstname`, `lastname`, `email`, `password`, `createdAt`, `updatedAt` FROM `users` AS `user` WHERE `user`.`email` = 'mosta1996@hotmail.com' LIMIT 1;"},"original":{"code":"ER_NO_SUCH_TABLE","errno":1146,"sqlState":"42S02","sqlMessage":"Table 'test_db.users' doesn't exist","sql":"SELECT `id`, `firstname`, `lastname`, `email`, `password`, `createdAt`, `updatedAt` FROM `users` AS `user` WHERE `user`.`email` = 'mosta1996@hotmail.com' LIMIT 1;"},"sql":"SELECT `id`, `firstname`, `lastname`, `email`, `password`, `createdAt`, `updatedAt` FROM `users` AS `user` WHERE `user`.`email` = 'mosta1996@hotmail.com' LIMIT 1;","level":"\u001b[31merror\u001b[39m","message":"Table 'test_db.users' doesn't exist Table 'test_db.users' doesn't exist","stack":"SequelizeDatabaseError: Table 'test_db.users' doesn't exist\n    at Query.formatError (/server/node_modules/sequelize/lib/dialects/mysql/query.js:265:16)\n    at Query.run (/server/node_modules/sequelize/lib/dialects/mysql/query.js:77:18)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async /server/node_modules/sequelize/lib/sequelize.js:619:16\n    at async MySQLQueryInterface.select (/server/node_modules/sequelize/lib/dialects/abstract/query-interface.js:953:12)\n    at async Function.findAll (/server/node_modules/sequelize/lib/model.js:1753:21)\n    at async Function.findOne (/server/node_modules/sequelize/lib/model.js:1917:12)\n    at async UserAdapter.getOne (/server/server/adapters/mysql_database/BaseAdapter.js:38:24)\n    at async UserAdapter.getOne (/server/server/adapters/mysql_database/user.adapter.js:33:20)\n    at async UserController.getOne (/server/server/controllers/Controller.js:41:24)","timestamp":"2021-09-12T18:28:07.679Z"}
{"name":"SequelizeDatabaseError","parent":{"code":"ER_NO_SUCH_TABLE","errno":1146,"sqlState":"42S02","sqlMessage":"Table 'test_db.users' doesn't exist","sql":"SELECT `id`, `firstname`, `lastname`, `email`, `password`, `createdAt`, `updatedAt` FROM `users` AS `user` WHERE `user`.`email` = 'mosta1996@hotmail.com' LIMIT 1;"},"original":{"code":"ER_NO_SUCH_TABLE","errno":1146,"sqlState":"42S02","sqlMessage":"Table 'test_db.users' doesn't exist","sql":"SELECT `id`, `firstname`, `lastname`, `email`, `password`, `createdAt`, `updatedAt` FROM `users` AS `user` WHERE `user`.`email` = 'mosta1996@hotmail.com' LIMIT 1;"},"sql":"SELECT `id`, `firstname`, `lastname`, `email`, `password`, `createdAt`, `updatedAt` FROM `users` AS `user` WHERE `user`.`email` = 'mosta1996@hotmail.com' LIMIT 1;","level":"\u001b[31merror\u001b[39m","message":"Table 'test_db.users' doesn't exist Table 'test_db.users' doesn't exist","stack":"SequelizeDatabaseError: Table 'test_db.users' doesn't exist\n    at Query.formatError (/server/node_modules/sequelize/lib/dialects/mysql/query.js:265:16)\n    at Query.run (/server/node_modules/sequelize/lib/dialects/mysql/query.js:77:18)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async /server/node_modules/sequelize/lib/sequelize.js:619:16\n    at async MySQLQueryInterface.select (/server/node_modules/sequelize/lib/dialects/abstract/query-interface.js:953:12)\n    at async Function.findAll (/server/node_modules/sequelize/lib/model.js:1753:21)\n    at async Function.findOne (/server/node_modules/sequelize/lib/model.js:1917:12)\n    at async UserAdapter.getOne (/server/server/adapters/mysql_database/BaseAdapter.js:38:24)\n    at async UserAdapter.getOne (/server/server/adapters/mysql_database/user.adapter.js:33:20)\n    at async UserController.getOne (/server/server/controllers/Controller.js:41:24)","timestamp":"2021-09-12T18:28:07.679Z"}
{"name":"SequelizeConnectionError","parent":{"errno":-3001,"code":"EAI_AGAIN","syscall":"getaddrinfo","hostname":"mysql-database","fatal":true},"original":{"errno":-3001,"code":"EAI_AGAIN","syscall":"getaddrinfo","hostname":"mysql-database","fatal":true},"level":"\u001b[31merror\u001b[39m","message":"Unable to connect to the database: getaddrinfo EAI_AGAIN mysql-database","stack":"SequelizeConnectionError: getaddrinfo EAI_AGAIN mysql-database\n    at ConnectionManager.connect (/server/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:126:17)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async ConnectionManager._connect (/server/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:318:24)\n    at async /server/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:250:32\n    at async ConnectionManager.getConnection (/server/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:280:7)\n    at async /server/node_modules/sequelize/lib/sequelize.js:613:26\n    at async Sequelize.authenticate (/server/node_modules/sequelize/lib/sequelize.js:867:5)","timestamp":"2021-09-12T18:37:28.880Z"}
{"name":"SequelizeDatabaseError","parent":{"code":"ER_NO_SUCH_TABLE","errno":1146,"sqlState":"42S02","sqlMessage":"Table 'test_db.users' doesn't exist","sql":"SELECT `id`, `firstname`, `lastname`, `email`, `password`, `createdAt`, `updatedAt` FROM `users` AS `user` WHERE `user`.`email` = 'mosta1996@hotmail.com' LIMIT 1;"},"original":{"code":"ER_NO_SUCH_TABLE","errno":1146,"sqlState":"42S02","sqlMessage":"Table 'test_db.users' doesn't exist","sql":"SELECT `id`, `firstname`, `lastname`, `email`, `password`, `createdAt`, `updatedAt` FROM `users` AS `user` WHERE `user`.`email` = 'mosta1996@hotmail.com' LIMIT 1;"},"sql":"SELECT `id`, `firstname`, `lastname`, `email`, `password`, `createdAt`, `updatedAt` FROM `users` AS `user` WHERE `user`.`email` = 'mosta1996@hotmail.com' LIMIT 1;","level":"\u001b[31merror\u001b[39m","message":"Table 'test_db.users' doesn't exist Table 'test_db.users' doesn't exist","stack":"SequelizeDatabaseError: Table 'test_db.users' doesn't exist\n    at Query.formatError (/server/node_modules/sequelize/lib/dialects/mysql/query.js:265:16)\n    at Query.run (/server/node_modules/sequelize/lib/dialects/mysql/query.js:77:18)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async /server/node_modules/sequelize/lib/sequelize.js:619:16\n    at async MySQLQueryInterface.select (/server/node_modules/sequelize/lib/dialects/abstract/query-interface.js:953:12)\n    at async Function.findAll (/server/node_modules/sequelize/lib/model.js:1753:21)\n    at async Function.findOne (/server/node_modules/sequelize/lib/model.js:1917:12)\n    at async UserAdapter.getOne (/server/server/adapters/mysql_database/BaseAdapter.js:38:24)\n    at async UserAdapter.getOne (/server/server/adapters/mysql_database/user.adapter.js:33:20)\n    at async UserController.getOne (/server/server/controllers/Controller.js:41:24)","timestamp":"2021-09-12T21:11:04.246Z"}
{"name":"SequelizeDatabaseError","parent":{"code":"ER_NO_SUCH_TABLE","errno":1146,"sqlState":"42S02","sqlMessage":"Table 'test_db.users' doesn't exist","sql":"SELECT `id`, `firstname`, `lastname`, `email`, `password`, `createdAt`, `updatedAt` FROM `users` AS `user` WHERE `user`.`email` = 'mosta1996@hotmail.com' LIMIT 1;"},"original":{"code":"ER_NO_SUCH_TABLE","errno":1146,"sqlState":"42S02","sqlMessage":"Table 'test_db.users' doesn't exist","sql":"SELECT `id`, `firstname`, `lastname`, `email`, `password`, `createdAt`, `updatedAt` FROM `users` AS `user` WHERE `user`.`email` = 'mosta1996@hotmail.com' LIMIT 1;"},"sql":"SELECT `id`, `firstname`, `lastname`, `email`, `password`, `createdAt`, `updatedAt` FROM `users` AS `user` WHERE `user`.`email` = 'mosta1996@hotmail.com' LIMIT 1;","level":"\u001b[31merror\u001b[39m","message":"Table 'test_db.users' doesn't exist Table 'test_db.users' doesn't exist","stack":"SequelizeDatabaseError: Table 'test_db.users' doesn't exist\n    at Query.formatError (/server/node_modules/sequelize/lib/dialects/mysql/query.js:265:16)\n    at Query.run (/server/node_modules/sequelize/lib/dialects/mysql/query.js:77:18)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async /server/node_modules/sequelize/lib/sequelize.js:619:16\n    at async MySQLQueryInterface.select (/server/node_modules/sequelize/lib/dialects/abstract/query-interface.js:953:12)\n    at async Function.findAll (/server/node_modules/sequelize/lib/model.js:1753:21)\n    at async Function.findOne (/server/node_modules/sequelize/lib/model.js:1917:12)\n    at async UserAdapter.getOne (/server/server/adapters/mysql_database/BaseAdapter.js:38:24)\n    at async UserAdapter.getOne (/server/server/adapters/mysql_database/user.adapter.js:33:20)\n    at async UserController.getOne (/server/server/controllers/Controller.js:41:24)","timestamp":"2021-09-12T21:11:04.247Z"}
{"name":"SequelizeDatabaseError","parent":{"code":"ER_NO_SUCH_TABLE","errno":1146,"sqlState":"42S02","sqlMessage":"Table 'test_db.users' doesn't exist","sql":"SELECT `id`, `firstname`, `lastname`, `email`, `password`, `createdAt`, `updatedAt` FROM `users` AS `user` WHERE `user`.`email` = 'mosta1996@hotmail.com' LIMIT 1;"},"original":{"code":"ER_NO_SUCH_TABLE","errno":1146,"sqlState":"42S02","sqlMessage":"Table 'test_db.users' doesn't exist","sql":"SELECT `id`, `firstname`, `lastname`, `email`, `password`, `createdAt`, `updatedAt` FROM `users` AS `user` WHERE `user`.`email` = 'mosta1996@hotmail.com' LIMIT 1;"},"sql":"SELECT `id`, `firstname`, `lastname`, `email`, `password`, `createdAt`, `updatedAt` FROM `users` AS `user` WHERE `user`.`email` = 'mosta1996@hotmail.com' LIMIT 1;","level":"\u001b[31merror\u001b[39m","message":"Table 'test_db.users' doesn't exist Table 'test_db.users' doesn't exist","stack":"SequelizeDatabaseError: Table 'test_db.users' doesn't exist\n    at Query.formatError (/server/node_modules/sequelize/lib/dialects/mysql/query.js:265:16)\n    at Query.run (/server/node_modules/sequelize/lib/dialects/mysql/query.js:77:18)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async /server/node_modules/sequelize/lib/sequelize.js:619:16\n    at async MySQLQueryInterface.select (/server/node_modules/sequelize/lib/dialects/abstract/query-interface.js:953:12)\n    at async Function.findAll (/server/node_modules/sequelize/lib/model.js:1753:21)\n    at async Function.findOne (/server/node_modules/sequelize/lib/model.js:1917:12)\n    at async UserAdapter.getOne (/server/server/adapters/mysql_database/BaseAdapter.js:38:24)\n    at async UserAdapter.getOne (/server/server/adapters/mysql_database/user.adapter.js:33:20)\n    at async UserController.getOne (/server/server/controllers/Controller.js:41:24)","timestamp":"2021-09-12T21:11:04.248Z"}
{"name":"SequelizeDatabaseError","parent":{"code":"ER_NO_SUCH_TABLE","errno":1146,"sqlState":"42S02","sqlMessage":"Table 'test_db.users' doesn't exist","sql":"SELECT `id`, `firstname`, `lastname`, `email`, `password`, `createdAt`, `updatedAt` FROM `users` AS `user` WHERE `user`.`email` = 'mosta1996@hotmail.com' LIMIT 1;"},"original":{"code":"ER_NO_SUCH_TABLE","errno":1146,"sqlState":"42S02","sqlMessage":"Table 'test_db.users' doesn't exist","sql":"SELECT `id`, `firstname`, `lastname`, `email`, `password`, `createdAt`, `updatedAt` FROM `users` AS `user` WHERE `user`.`email` = 'mosta1996@hotmail.com' LIMIT 1;"},"sql":"SELECT `id`, `firstname`, `lastname`, `email`, `password`, `createdAt`, `updatedAt` FROM `users` AS `user` WHERE `user`.`email` = 'mosta1996@hotmail.com' LIMIT 1;","level":"\u001b[31merror\u001b[39m","message":"Table 'test_db.users' doesn't exist Table 'test_db.users' doesn't exist","stack":"SequelizeDatabaseError: Table 'test_db.users' doesn't exist\n    at Query.formatError (/server/node_modules/sequelize/lib/dialects/mysql/query.js:265:16)\n    at Query.run (/server/node_modules/sequelize/lib/dialects/mysql/query.js:77:18)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async /server/node_modules/sequelize/lib/sequelize.js:619:16\n    at async MySQLQueryInterface.select (/server/node_modules/sequelize/lib/dialects/abstract/query-interface.js:953:12)\n    at async Function.findAll (/server/node_modules/sequelize/lib/model.js:1753:21)\n    at async Function.findOne (/server/node_modules/sequelize/lib/model.js:1917:12)\n    at async UserAdapter.getOne (/server/server/adapters/mysql_database/BaseAdapter.js:38:24)\n    at async UserAdapter.getOne (/server/server/adapters/mysql_database/user.adapter.js:33:20)\n    at async UserController.getOne (/server/server/controllers/Controller.js:41:24)","timestamp":"2021-09-12T21:11:04.248Z"}
{"name":"SequelizeDatabaseError","parent":{"code":"ER_NO_SUCH_TABLE","errno":1146,"sqlState":"42S02","sqlMessage":"Table 'test_db.users' doesn't exist","sql":"SELECT `id`, `firstname`, `lastname`, `email`, `password`, `createdAt`, `updatedAt` FROM `users` AS `user` WHERE `user`.`email` = 'mosta1996@hotmail.com';"},"original":{"code":"ER_NO_SUCH_TABLE","errno":1146,"sqlState":"42S02","sqlMessage":"Table 'test_db.users' doesn't exist","sql":"SELECT `id`, `firstname`, `lastname`, `email`, `password`, `createdAt`, `updatedAt` FROM `users` AS `user` WHERE `user`.`email` = 'mosta1996@hotmail.com';"},"sql":"SELECT `id`, `firstname`, `lastname`, `email`, `password`, `createdAt`, `updatedAt` FROM `users` AS `user` WHERE `user`.`email` = 'mosta1996@hotmail.com';","level":"\u001b[31merror\u001b[39m","message":"Table 'test_db.users' doesn't exist Table 'test_db.users' doesn't exist","stack":"SequelizeDatabaseError: Table 'test_db.users' doesn't exist\n    at Query.formatError (/server/node_modules/sequelize/lib/dialects/mysql/query.js:265:16)\n    at Query.run (/server/node_modules/sequelize/lib/dialects/mysql/query.js:77:18)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async /server/node_modules/sequelize/lib/sequelize.js:619:16\n    at async MySQLQueryInterface.select (/server/node_modules/sequelize/lib/dialects/abstract/query-interface.js:953:12)\n    at async Function.findAll (/server/node_modules/sequelize/lib/model.js:1753:21)\n    at async Function.findOne (/server/node_modules/sequelize/lib/model.js:1917:12)\n    at async UserAdapter.getOne (/server/server/adapters/mysql_database/BaseAdapter.js:38:24)\n    at async UserAdapter.getOne (/server/server/adapters/mysql_database/user.adapter.js:33:20)\n    at async UserController.getOne (/server/server/controllers/Controller.js:41:24)","timestamp":"2021-09-14T13:12:25.411Z"}
{"name":"SequelizeDatabaseError","parent":{"code":"ER_NO_SUCH_TABLE","errno":1146,"sqlState":"42S02","sqlMessage":"Table 'test_db.users' doesn't exist","sql":"SELECT `id`, `firstname`, `lastname`, `email`, `password`, `createdAt`, `updatedAt` FROM `users` AS `user` WHERE `user`.`email` = 'mosta1996@hotmail.com';"},"original":{"code":"ER_NO_SUCH_TABLE","errno":1146,"sqlState":"42S02","sqlMessage":"Table 'test_db.users' doesn't exist","sql":"SELECT `id`, `firstname`, `lastname`, `email`, `password`, `createdAt`, `updatedAt` FROM `users` AS `user` WHERE `user`.`email` = 'mosta1996@hotmail.com';"},"sql":"SELECT `id`, `firstname`, `lastname`, `email`, `password`, `createdAt`, `updatedAt` FROM `users` AS `user` WHERE `user`.`email` = 'mosta1996@hotmail.com';","level":"\u001b[31merror\u001b[39m","message":"Table 'test_db.users' doesn't exist Table 'test_db.users' doesn't exist","stack":"SequelizeDatabaseError: Table 'test_db.users' doesn't exist\n    at Query.formatError (/server/node_modules/sequelize/lib/dialects/mysql/query.js:265:16)\n    at Query.run (/server/node_modules/sequelize/lib/dialects/mysql/query.js:77:18)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async /server/node_modules/sequelize/lib/sequelize.js:619:16\n    at async MySQLQueryInterface.select (/server/node_modules/sequelize/lib/dialects/abstract/query-interface.js:953:12)\n    at async Function.findAll (/server/node_modules/sequelize/lib/model.js:1753:21)\n    at async Function.findOne (/server/node_modules/sequelize/lib/model.js:1917:12)\n    at async UserAdapter.getOne (/server/server/adapters/mysql_database/BaseAdapter.js:38:24)\n    at async UserAdapter.getOne (/server/server/adapters/mysql_database/user.adapter.js:33:20)\n    at async UserController.getOne (/server/server/controllers/Controller.js:41:24)","timestamp":"2021-09-14T13:12:25.413Z"}
{"name":"SequelizeDatabaseError","parent":{"code":"ER_NO_SUCH_TABLE","errno":1146,"sqlState":"42S02","sqlMessage":"Table 'test_db.users' doesn't exist","sql":"SELECT `id`, `firstname`, `lastname`, `email`, `password`, `createdAt`, `updatedAt` FROM `users` AS `user` WHERE `user`.`email` = 'mosta1996@hotmail.com';"},"original":{"code":"ER_NO_SUCH_TABLE","errno":1146,"sqlState":"42S02","sqlMessage":"Table 'test_db.users' doesn't exist","sql":"SELECT `id`, `firstname`, `lastname`, `email`, `password`, `createdAt`, `updatedAt` FROM `users` AS `user` WHERE `user`.`email` = 'mosta1996@hotmail.com';"},"sql":"SELECT `id`, `firstname`, `lastname`, `email`, `password`, `createdAt`, `updatedAt` FROM `users` AS `user` WHERE `user`.`email` = 'mosta1996@hotmail.com';","level":"\u001b[31merror\u001b[39m","message":"Table 'test_db.users' doesn't exist Table 'test_db.users' doesn't exist","stack":"SequelizeDatabaseError: Table 'test_db.users' doesn't exist\n    at Query.formatError (/server/node_modules/sequelize/lib/dialects/mysql/query.js:265:16)\n    at Query.run (/server/node_modules/sequelize/lib/dialects/mysql/query.js:77:18)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async /server/node_modules/sequelize/lib/sequelize.js:619:16\n    at async MySQLQueryInterface.select (/server/node_modules/sequelize/lib/dialects/abstract/query-interface.js:953:12)\n    at async Function.findAll (/server/node_modules/sequelize/lib/model.js:1753:21)\n    at async Function.findOne (/server/node_modules/sequelize/lib/model.js:1917:12)\n    at async UserAdapter.getOne (/server/server/adapters/mysql_database/BaseAdapter.js:38:24)\n    at async UserAdapter.getOne (/server/server/adapters/mysql_database/user.adapter.js:33:20)\n    at async UserController.getOne (/server/server/controllers/Controller.js:41:24)","timestamp":"2021-09-14T13:12:25.414Z"}
{"name":"SequelizeDatabaseError","parent":{"code":"ER_NO_SUCH_TABLE","errno":1146,"sqlState":"42S02","sqlMessage":"Table 'test_db.users' doesn't exist","sql":"SELECT `id`, `firstname`, `lastname`, `email`, `password`, `createdAt`, `updatedAt` FROM `users` AS `user` WHERE `user`.`email` = 'mosta1996@hotmail.com';"},"original":{"code":"ER_NO_SUCH_TABLE","errno":1146,"sqlState":"42S02","sqlMessage":"Table 'test_db.users' doesn't exist","sql":"SELECT `id`, `firstname`, `lastname`, `email`, `password`, `createdAt`, `updatedAt` FROM `users` AS `user` WHERE `user`.`email` = 'mosta1996@hotmail.com';"},"sql":"SELECT `id`, `firstname`, `lastname`, `email`, `password`, `createdAt`, `updatedAt` FROM `users` AS `user` WHERE `user`.`email` = 'mosta1996@hotmail.com';","level":"\u001b[31merror\u001b[39m","message":"Table 'test_db.users' doesn't exist Table 'test_db.users' doesn't exist","stack":"SequelizeDatabaseError: Table 'test_db.users' doesn't exist\n    at Query.formatError (/server/node_modules/sequelize/lib/dialects/mysql/query.js:265:16)\n    at Query.run (/server/node_modules/sequelize/lib/dialects/mysql/query.js:77:18)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async /server/node_modules/sequelize/lib/sequelize.js:619:16\n    at async MySQLQueryInterface.select (/server/node_modules/sequelize/lib/dialects/abstract/query-interface.js:953:12)\n    at async Function.findAll (/server/node_modules/sequelize/lib/model.js:1753:21)\n    at async Function.findOne (/server/node_modules/sequelize/lib/model.js:1917:12)\n    at async UserAdapter.getOne (/server/server/adapters/mysql_database/BaseAdapter.js:38:24)\n    at async UserAdapter.getOne (/server/server/adapters/mysql_database/user.adapter.js:33:20)\n    at async UserController.getOne (/server/server/controllers/Controller.js:41:24)","timestamp":"2021-09-14T13:12:25.414Z"}
{"level":"\u001b[31merror\u001b[39m","message":"Logger level is invalid Logger level is invalid","stack":"Error: Logger level is invalid\n    at Logger.log (/server/logger/logger-init.js:63:15)\n    at UserController.createUser (/server/server/controllers/user.controller.js:18:14)\n    at /server/server/routers/user.js:12:39\n    at Layer.handle [as handle_request] (/server/node_modules/express/lib/router/layer.js:95:5)\n    at next (/server/node_modules/express/lib/router/route.js:137:13)\n    at validateRequest (/server/server/schemas/validateRequest.js:14:10)\n    at userCreateSchema (/server/server/schemas/user.js:11:3)\n    at Layer.handle [as handle_request] (/server/node_modules/express/lib/router/layer.js:95:5)\n    at next (/server/node_modules/express/lib/router/route.js:137:13)\n    at Route.dispatch (/server/node_modules/express/lib/router/route.js:112:3)","timestamp":"2021-09-14T13:18:37.745Z"}
{"name":"SequelizeDatabaseError","parent":{"code":"ER_NO_SUCH_TABLE","errno":1146,"sqlState":"42S02","sqlMessage":"Table 'test_db.users' doesn't exist","sql":"SELECT `id`, `firstname`, `lastname`, `email`, `password`, `createdAt`, `updatedAt` FROM `users` AS `user` WHERE `user`.`email` = 'mosta1996@hotmail.com';"},"original":{"code":"ER_NO_SUCH_TABLE","errno":1146,"sqlState":"42S02","sqlMessage":"Table 'test_db.users' doesn't exist","sql":"SELECT `id`, `firstname`, `lastname`, `email`, `password`, `createdAt`, `updatedAt` FROM `users` AS `user` WHERE `user`.`email` = 'mosta1996@hotmail.com';"},"sql":"SELECT `id`, `firstname`, `lastname`, `email`, `password`, `createdAt`, `updatedAt` FROM `users` AS `user` WHERE `user`.`email` = 'mosta1996@hotmail.com';","level":"\u001b[31merror\u001b[39m","message":"Table 'test_db.users' doesn't exist Table 'test_db.users' doesn't exist","stack":"SequelizeDatabaseError: Table 'test_db.users' doesn't exist\n    at Query.formatError (/server/node_modules/sequelize/lib/dialects/mysql/query.js:265:16)\n    at Query.run (/server/node_modules/sequelize/lib/dialects/mysql/query.js:77:18)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async /server/node_modules/sequelize/lib/sequelize.js:619:16\n    at async MySQLQueryInterface.select (/server/node_modules/sequelize/lib/dialects/abstract/query-interface.js:953:12)\n    at async Function.findAll (/server/node_modules/sequelize/lib/model.js:1753:21)\n    at async Function.findOne (/server/node_modules/sequelize/lib/model.js:1917:12)\n    at async UserAdapter.getOne (/server/server/adapters/mysql_database/BaseAdapter.js:38:24)\n    at async UserAdapter.getOne (/server/server/adapters/mysql_database/user.adapter.js:33:20)\n    at async UserController.getOne (/server/server/controllers/Controller.js:41:24)","timestamp":"2021-09-14T13:18:37.761Z"}
{"name":"SequelizeDatabaseError","parent":{"code":"ER_NO_SUCH_TABLE","errno":1146,"sqlState":"42S02","sqlMessage":"Table 'test_db.users' doesn't exist","sql":"SELECT `id`, `firstname`, `lastname`, `email`, `password`, `createdAt`, `updatedAt` FROM `users` AS `user` WHERE `user`.`email` = 'mosta1996@hotmail.com';"},"original":{"code":"ER_NO_SUCH_TABLE","errno":1146,"sqlState":"42S02","sqlMessage":"Table 'test_db.users' doesn't exist","sql":"SELECT `id`, `firstname`, `lastname`, `email`, `password`, `createdAt`, `updatedAt` FROM `users` AS `user` WHERE `user`.`email` = 'mosta1996@hotmail.com';"},"sql":"SELECT `id`, `firstname`, `lastname`, `email`, `password`, `createdAt`, `updatedAt` FROM `users` AS `user` WHERE `user`.`email` = 'mosta1996@hotmail.com';","level":"\u001b[31merror\u001b[39m","message":"Table 'test_db.users' doesn't exist Table 'test_db.users' doesn't exist","stack":"SequelizeDatabaseError: Table 'test_db.users' doesn't exist\n    at Query.formatError (/server/node_modules/sequelize/lib/dialects/mysql/query.js:265:16)\n    at Query.run (/server/node_modules/sequelize/lib/dialects/mysql/query.js:77:18)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async /server/node_modules/sequelize/lib/sequelize.js:619:16\n    at async MySQLQueryInterface.select (/server/node_modules/sequelize/lib/dialects/abstract/query-interface.js:953:12)\n    at async Function.findAll (/server/node_modules/sequelize/lib/model.js:1753:21)\n    at async Function.findOne (/server/node_modules/sequelize/lib/model.js:1917:12)\n    at async UserAdapter.getOne (/server/server/adapters/mysql_database/BaseAdapter.js:38:24)\n    at async UserAdapter.getOne (/server/server/adapters/mysql_database/user.adapter.js:33:20)\n    at async UserController.getOne (/server/server/controllers/Controller.js:41:24)","timestamp":"2021-09-14T13:18:37.762Z"}
{"name":"SequelizeDatabaseError","parent":{"code":"ER_NO_SUCH_TABLE","errno":1146,"sqlState":"42S02","sqlMessage":"Table 'test_db.users' doesn't exist","sql":"SELECT `id`, `firstname`, `lastname`, `email`, `password`, `createdAt`, `updatedAt` FROM `users` AS `user` WHERE `user`.`email` = 'mosta1996@hotmail.com';"},"original":{"code":"ER_NO_SUCH_TABLE","errno":1146,"sqlState":"42S02","sqlMessage":"Table 'test_db.users' doesn't exist","sql":"SELECT `id`, `firstname`, `lastname`, `email`, `password`, `createdAt`, `updatedAt` FROM `users` AS `user` WHERE `user`.`email` = 'mosta1996@hotmail.com';"},"sql":"SELECT `id`, `firstname`, `lastname`, `email`, `password`, `createdAt`, `updatedAt` FROM `users` AS `user` WHERE `user`.`email` = 'mosta1996@hotmail.com';","level":"\u001b[31merror\u001b[39m","message":"Table 'test_db.users' doesn't exist Table 'test_db.users' doesn't exist","stack":"SequelizeDatabaseError: Table 'test_db.users' doesn't exist\n    at Query.formatError (/server/node_modules/sequelize/lib/dialects/mysql/query.js:265:16)\n    at Query.run (/server/node_modules/sequelize/lib/dialects/mysql/query.js:77:18)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async /server/node_modules/sequelize/lib/sequelize.js:619:16\n    at async MySQLQueryInterface.select (/server/node_modules/sequelize/lib/dialects/abstract/query-interface.js:953:12)\n    at async Function.findAll (/server/node_modules/sequelize/lib/model.js:1753:21)\n    at async Function.findOne (/server/node_modules/sequelize/lib/model.js:1917:12)\n    at async UserAdapter.getOne (/server/server/adapters/mysql_database/BaseAdapter.js:38:24)\n    at async UserAdapter.getOne (/server/server/adapters/mysql_database/user.adapter.js:33:20)\n    at async UserController.getOne (/server/server/controllers/Controller.js:41:24)","timestamp":"2021-09-14T13:18:37.763Z"}
{"name":"SequelizeDatabaseError","parent":{"code":"ER_NO_SUCH_TABLE","errno":1146,"sqlState":"42S02","sqlMessage":"Table 'test_db.users' doesn't exist","sql":"SELECT `id`, `firstname`, `lastname`, `email`, `password`, `createdAt`, `updatedAt` FROM `users` AS `user` WHERE `user`.`email` = 'mosta1996@hotmail.com';"},"original":{"code":"ER_NO_SUCH_TABLE","errno":1146,"sqlState":"42S02","sqlMessage":"Table 'test_db.users' doesn't exist","sql":"SELECT `id`, `firstname`, `lastname`, `email`, `password`, `createdAt`, `updatedAt` FROM `users` AS `user` WHERE `user`.`email` = 'mosta1996@hotmail.com';"},"sql":"SELECT `id`, `firstname`, `lastname`, `email`, `password`, `createdAt`, `updatedAt` FROM `users` AS `user` WHERE `user`.`email` = 'mosta1996@hotmail.com';","level":"\u001b[31merror\u001b[39m","message":"Table 'test_db.users' doesn't exist Table 'test_db.users' doesn't exist","stack":"SequelizeDatabaseError: Table 'test_db.users' doesn't exist\n    at Query.formatError (/server/node_modules/sequelize/lib/dialects/mysql/query.js:265:16)\n    at Query.run (/server/node_modules/sequelize/lib/dialects/mysql/query.js:77:18)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async /server/node_modules/sequelize/lib/sequelize.js:619:16\n    at async MySQLQueryInterface.select (/server/node_modules/sequelize/lib/dialects/abstract/query-interface.js:953:12)\n    at async Function.findAll (/server/node_modules/sequelize/lib/model.js:1753:21)\n    at async Function.findOne (/server/node_modules/sequelize/lib/model.js:1917:12)\n    at async UserAdapter.getOne (/server/server/adapters/mysql_database/BaseAdapter.js:38:24)\n    at async UserAdapter.getOne (/server/server/adapters/mysql_database/user.adapter.js:33:20)\n    at async UserController.getOne (/server/server/controllers/Controller.js:41:24)","timestamp":"2021-09-14T13:18:37.763Z"}
{"name":"SequelizeDatabaseError","parent":{"code":"ER_NO_SUCH_TABLE","errno":1146,"sqlState":"42S02","sqlMessage":"Table 'test_db.users' doesn't exist","sql":"SELECT `id`, `firstname`, `lastname`, `email`, `password`, `createdAt`, `updatedAt` FROM `users` AS `user` WHERE `user`.`email` = 'mosta1996@hotmail.com';"},"original":{"code":"ER_NO_SUCH_TABLE","errno":1146,"sqlState":"42S02","sqlMessage":"Table 'test_db.users' doesn't exist","sql":"SELECT `id`, `firstname`, `lastname`, `email`, `password`, `createdAt`, `updatedAt` FROM `users` AS `user` WHERE `user`.`email` = 'mosta1996@hotmail.com';"},"sql":"SELECT `id`, `firstname`, `lastname`, `email`, `password`, `createdAt`, `updatedAt` FROM `users` AS `user` WHERE `user`.`email` = 'mosta1996@hotmail.com';","level":"\u001b[31merror\u001b[39m","message":"Table 'test_db.users' doesn't exist Table 'test_db.users' doesn't exist","stack":"SequelizeDatabaseError: Table 'test_db.users' doesn't exist\n    at Query.formatError (/server/node_modules/sequelize/lib/dialects/mysql/query.js:265:16)\n    at Query.run (/server/node_modules/sequelize/lib/dialects/mysql/query.js:77:18)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async /server/node_modules/sequelize/lib/sequelize.js:619:16\n    at async MySQLQueryInterface.select (/server/node_modules/sequelize/lib/dialects/abstract/query-interface.js:953:12)\n    at async Function.findAll (/server/node_modules/sequelize/lib/model.js:1753:21)\n    at async Function.findOne (/server/node_modules/sequelize/lib/model.js:1917:12)\n    at async UserAdapter.getOne (/server/server/adapters/mysql_database/BaseAdapter.js:38:24)\n    at async UserAdapter.getOne (/server/server/adapters/mysql_database/user.adapter.js:33:20)\n    at async UserController.getOne (/server/server/controllers/Controller.js:41:24)","timestamp":"2021-09-14T13:19:02.973Z"}
{"name":"SequelizeDatabaseError","parent":{"code":"ER_NO_SUCH_TABLE","errno":1146,"sqlState":"42S02","sqlMessage":"Table 'test_db.users' doesn't exist","sql":"SELECT `id`, `firstname`, `lastname`, `email`, `password`, `createdAt`, `updatedAt` FROM `users` AS `user` WHERE `user`.`email` = 'mosta1996@hotmail.com';"},"original":{"code":"ER_NO_SUCH_TABLE","errno":1146,"sqlState":"42S02","sqlMessage":"Table 'test_db.users' doesn't exist","sql":"SELECT `id`, `firstname`, `lastname`, `email`, `password`, `createdAt`, `updatedAt` FROM `users` AS `user` WHERE `user`.`email` = 'mosta1996@hotmail.com';"},"sql":"SELECT `id`, `firstname`, `lastname`, `email`, `password`, `createdAt`, `updatedAt` FROM `users` AS `user` WHERE `user`.`email` = 'mosta1996@hotmail.com';","level":"\u001b[31merror\u001b[39m","message":"Table 'test_db.users' doesn't exist Table 'test_db.users' doesn't exist","stack":"SequelizeDatabaseError: Table 'test_db.users' doesn't exist\n    at Query.formatError (/server/node_modules/sequelize/lib/dialects/mysql/query.js:265:16)\n    at Query.run (/server/node_modules/sequelize/lib/dialects/mysql/query.js:77:18)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async /server/node_modules/sequelize/lib/sequelize.js:619:16\n    at async MySQLQueryInterface.select (/server/node_modules/sequelize/lib/dialects/abstract/query-interface.js:953:12)\n    at async Function.findAll (/server/node_modules/sequelize/lib/model.js:1753:21)\n    at async Function.findOne (/server/node_modules/sequelize/lib/model.js:1917:12)\n    at async UserAdapter.getOne (/server/server/adapters/mysql_database/BaseAdapter.js:38:24)\n    at async UserAdapter.getOne (/server/server/adapters/mysql_database/user.adapter.js:33:20)\n    at async UserController.getOne (/server/server/controllers/Controller.js:41:24)","timestamp":"2021-09-14T13:19:02.974Z"}
{"name":"SequelizeDatabaseError","parent":{"code":"ER_NO_SUCH_TABLE","errno":1146,"sqlState":"42S02","sqlMessage":"Table 'test_db.users' doesn't exist","sql":"SELECT `id`, `firstname`, `lastname`, `email`, `password`, `createdAt`, `updatedAt` FROM `users` AS `user` WHERE `user`.`email` = 'mosta1996@hotmail.com';"},"original":{"code":"ER_NO_SUCH_TABLE","errno":1146,"sqlState":"42S02","sqlMessage":"Table 'test_db.users' doesn't exist","sql":"SELECT `id`, `firstname`, `lastname`, `email`, `password`, `createdAt`, `updatedAt` FROM `users` AS `user` WHERE `user`.`email` = 'mosta1996@hotmail.com';"},"sql":"SELECT `id`, `firstname`, `lastname`, `email`, `password`, `createdAt`, `updatedAt` FROM `users` AS `user` WHERE `user`.`email` = 'mosta1996@hotmail.com';","level":"\u001b[31merror\u001b[39m","message":"Table 'test_db.users' doesn't exist Table 'test_db.users' doesn't exist","stack":"SequelizeDatabaseError: Table 'test_db.users' doesn't exist\n    at Query.formatError (/server/node_modules/sequelize/lib/dialects/mysql/query.js:265:16)\n    at Query.run (/server/node_modules/sequelize/lib/dialects/mysql/query.js:77:18)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async /server/node_modules/sequelize/lib/sequelize.js:619:16\n    at async MySQLQueryInterface.select (/server/node_modules/sequelize/lib/dialects/abstract/query-interface.js:953:12)\n    at async Function.findAll (/server/node_modules/sequelize/lib/model.js:1753:21)\n    at async Function.findOne (/server/node_modules/sequelize/lib/model.js:1917:12)\n    at async UserAdapter.getOne (/server/server/adapters/mysql_database/BaseAdapter.js:38:24)\n    at async UserAdapter.getOne (/server/server/adapters/mysql_database/user.adapter.js:33:20)\n    at async UserController.getOne (/server/server/controllers/Controller.js:41:24)","timestamp":"2021-09-14T13:19:02.974Z"}
{"name":"SequelizeDatabaseError","parent":{"code":"ER_NO_SUCH_TABLE","errno":1146,"sqlState":"42S02","sqlMessage":"Table 'test_db.users' doesn't exist","sql":"SELECT `id`, `firstname`, `lastname`, `email`, `password`, `createdAt`, `updatedAt` FROM `users` AS `user` WHERE `user`.`email` = 'mosta1996@hotmail.com';"},"original":{"code":"ER_NO_SUCH_TABLE","errno":1146,"sqlState":"42S02","sqlMessage":"Table 'test_db.users' doesn't exist","sql":"SELECT `id`, `firstname`, `lastname`, `email`, `password`, `createdAt`, `updatedAt` FROM `users` AS `user` WHERE `user`.`email` = 'mosta1996@hotmail.com';"},"sql":"SELECT `id`, `firstname`, `lastname`, `email`, `password`, `createdAt`, `updatedAt` FROM `users` AS `user` WHERE `user`.`email` = 'mosta1996@hotmail.com';","level":"\u001b[31merror\u001b[39m","message":"Table 'test_db.users' doesn't exist Table 'test_db.users' doesn't exist","stack":"SequelizeDatabaseError: Table 'test_db.users' doesn't exist\n    at Query.formatError (/server/node_modules/sequelize/lib/dialects/mysql/query.js:265:16)\n    at Query.run (/server/node_modules/sequelize/lib/dialects/mysql/query.js:77:18)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async /server/node_modules/sequelize/lib/sequelize.js:619:16\n    at async MySQLQueryInterface.select (/server/node_modules/sequelize/lib/dialects/abstract/query-interface.js:953:12)\n    at async Function.findAll (/server/node_modules/sequelize/lib/model.js:1753:21)\n    at async Function.findOne (/server/node_modules/sequelize/lib/model.js:1917:12)\n    at async UserAdapter.getOne (/server/server/adapters/mysql_database/BaseAdapter.js:38:24)\n    at async UserAdapter.getOne (/server/server/adapters/mysql_database/user.adapter.js:33:20)\n    at async UserController.getOne (/server/server/controllers/Controller.js:41:24)","timestamp":"2021-09-14T13:19:02.975Z"}
{"name":"SequelizeDatabaseError","parent":{"code":"ER_NO_SUCH_TABLE","errno":1146,"sqlState":"42S02","sqlMessage":"Table 'test_db.users' doesn't exist","sql":"SELECT `id`, `firstname`, `lastname`, `email`, `password`, `createdAt`, `updatedAt` FROM `users` AS `user` WHERE `user`.`email` = 'mosta1996@hotmail.com';"},"original":{"code":"ER_NO_SUCH_TABLE","errno":1146,"sqlState":"42S02","sqlMessage":"Table 'test_db.users' doesn't exist","sql":"SELECT `id`, `firstname`, `lastname`, `email`, `password`, `createdAt`, `updatedAt` FROM `users` AS `user` WHERE `user`.`email` = 'mosta1996@hotmail.com';"},"sql":"SELECT `id`, `firstname`, `lastname`, `email`, `password`, `createdAt`, `updatedAt` FROM `users` AS `user` WHERE `user`.`email` = 'mosta1996@hotmail.com';","level":"\u001b[31merror\u001b[39m","message":"Table 'test_db.users' doesn't exist Table 'test_db.users' doesn't exist","stack":"SequelizeDatabaseError: Table 'test_db.users' doesn't exist\n    at Query.formatError (/server/node_modules/sequelize/lib/dialects/mysql/query.js:265:16)\n    at Query.run (/server/node_modules/sequelize/lib/dialects/mysql/query.js:77:18)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async /server/node_modules/sequelize/lib/sequelize.js:619:16\n    at async MySQLQueryInterface.select (/server/node_modules/sequelize/lib/dialects/abstract/query-interface.js:953:12)\n    at async Function.findAll (/server/node_modules/sequelize/lib/model.js:1753:21)\n    at async Function.findOne (/server/node_modules/sequelize/lib/model.js:1917:12)\n    at async UserAdapter.getOne (/server/server/adapters/mysql_database/BaseAdapter.js:39:24)\n    at async UserAdapter.getOne (/server/server/adapters/mysql_database/user.adapter.js:33:20)\n    at async UserController.getOne (/server/server/controllers/Controller.js:41:24)","timestamp":"2021-09-14T13:21:08.200Z"}
{"name":"SequelizeDatabaseError","parent":{"code":"ER_NO_SUCH_TABLE","errno":1146,"sqlState":"42S02","sqlMessage":"Table 'test_db.users' doesn't exist","sql":"SELECT `id`, `firstname`, `lastname`, `email`, `password`, `createdAt`, `updatedAt` FROM `users` AS `user` WHERE `user`.`email` = 'mosta1996@hotmail.com';"},"original":{"code":"ER_NO_SUCH_TABLE","errno":1146,"sqlState":"42S02","sqlMessage":"Table 'test_db.users' doesn't exist","sql":"SELECT `id`, `firstname`, `lastname`, `email`, `password`, `createdAt`, `updatedAt` FROM `users` AS `user` WHERE `user`.`email` = 'mosta1996@hotmail.com';"},"sql":"SELECT `id`, `firstname`, `lastname`, `email`, `password`, `createdAt`, `updatedAt` FROM `users` AS `user` WHERE `user`.`email` = 'mosta1996@hotmail.com';","level":"\u001b[31merror\u001b[39m","message":"Table 'test_db.users' doesn't exist Table 'test_db.users' doesn't exist","stack":"SequelizeDatabaseError: Table 'test_db.users' doesn't exist\n    at Query.formatError (/server/node_modules/sequelize/lib/dialects/mysql/query.js:265:16)\n    at Query.run (/server/node_modules/sequelize/lib/dialects/mysql/query.js:77:18)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async /server/node_modules/sequelize/lib/sequelize.js:619:16\n    at async MySQLQueryInterface.select (/server/node_modules/sequelize/lib/dialects/abstract/query-interface.js:953:12)\n    at async Function.findAll (/server/node_modules/sequelize/lib/model.js:1753:21)\n    at async Function.findOne (/server/node_modules/sequelize/lib/model.js:1917:12)\n    at async UserAdapter.getOne (/server/server/adapters/mysql_database/BaseAdapter.js:39:24)\n    at async UserAdapter.getOne (/server/server/adapters/mysql_database/user.adapter.js:33:20)\n    at async UserController.getOne (/server/server/controllers/Controller.js:41:24)","timestamp":"2021-09-14T13:21:08.201Z"}
{"name":"SequelizeDatabaseError","parent":{"code":"ER_NO_SUCH_TABLE","errno":1146,"sqlState":"42S02","sqlMessage":"Table 'test_db.users' doesn't exist","sql":"SELECT `id`, `firstname`, `lastname`, `email`, `password`, `createdAt`, `updatedAt` FROM `users` AS `user` WHERE `user`.`email` = 'mosta1996@hotmail.com';"},"original":{"code":"ER_NO_SUCH_TABLE","errno":1146,"sqlState":"42S02","sqlMessage":"Table 'test_db.users' doesn't exist","sql":"SELECT `id`, `firstname`, `lastname`, `email`, `password`, `createdAt`, `updatedAt` FROM `users` AS `user` WHERE `user`.`email` = 'mosta1996@hotmail.com';"},"sql":"SELECT `id`, `firstname`, `lastname`, `email`, `password`, `createdAt`, `updatedAt` FROM `users` AS `user` WHERE `user`.`email` = 'mosta1996@hotmail.com';","level":"\u001b[31merror\u001b[39m","message":"Table 'test_db.users' doesn't exist Table 'test_db.users' doesn't exist","stack":"SequelizeDatabaseError: Table 'test_db.users' doesn't exist\n    at Query.formatError (/server/node_modules/sequelize/lib/dialects/mysql/query.js:265:16)\n    at Query.run (/server/node_modules/sequelize/lib/dialects/mysql/query.js:77:18)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async /server/node_modules/sequelize/lib/sequelize.js:619:16\n    at async MySQLQueryInterface.select (/server/node_modules/sequelize/lib/dialects/abstract/query-interface.js:953:12)\n    at async Function.findAll (/server/node_modules/sequelize/lib/model.js:1753:21)\n    at async Function.findOne (/server/node_modules/sequelize/lib/model.js:1917:12)\n    at async UserAdapter.getOne (/server/server/adapters/mysql_database/BaseAdapter.js:39:24)\n    at async UserAdapter.getOne (/server/server/adapters/mysql_database/user.adapter.js:33:20)\n    at async UserController.getOne (/server/server/controllers/Controller.js:41:24)","timestamp":"2021-09-14T13:21:08.202Z"}
{"name":"SequelizeDatabaseError","parent":{"code":"ER_NO_SUCH_TABLE","errno":1146,"sqlState":"42S02","sqlMessage":"Table 'test_db.users' doesn't exist","sql":"SELECT `id`, `firstname`, `lastname`, `email`, `password`, `createdAt`, `updatedAt` FROM `users` AS `user` WHERE `user`.`email` = 'mosta1996@hotmail.com';"},"original":{"code":"ER_NO_SUCH_TABLE","errno":1146,"sqlState":"42S02","sqlMessage":"Table 'test_db.users' doesn't exist","sql":"SELECT `id`, `firstname`, `lastname`, `email`, `password`, `createdAt`, `updatedAt` FROM `users` AS `user` WHERE `user`.`email` = 'mosta1996@hotmail.com';"},"sql":"SELECT `id`, `firstname`, `lastname`, `email`, `password`, `createdAt`, `updatedAt` FROM `users` AS `user` WHERE `user`.`email` = 'mosta1996@hotmail.com';","level":"\u001b[31merror\u001b[39m","message":"Table 'test_db.users' doesn't exist Table 'test_db.users' doesn't exist","stack":"SequelizeDatabaseError: Table 'test_db.users' doesn't exist\n    at Query.formatError (/server/node_modules/sequelize/lib/dialects/mysql/query.js:265:16)\n    at Query.run (/server/node_modules/sequelize/lib/dialects/mysql/query.js:77:18)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async /server/node_modules/sequelize/lib/sequelize.js:619:16\n    at async MySQLQueryInterface.select (/server/node_modules/sequelize/lib/dialects/abstract/query-interface.js:953:12)\n    at async Function.findAll (/server/node_modules/sequelize/lib/model.js:1753:21)\n    at async Function.findOne (/server/node_modules/sequelize/lib/model.js:1917:12)\n    at async UserAdapter.getOne (/server/server/adapters/mysql_database/BaseAdapter.js:39:24)\n    at async UserAdapter.getOne (/server/server/adapters/mysql_database/user.adapter.js:33:20)\n    at async UserController.getOne (/server/server/controllers/Controller.js:41:24)","timestamp":"2021-09-14T13:21:08.202Z"}
{"name":"SequelizeDatabaseError","parent":{"code":"ER_NO_SUCH_TABLE","errno":1146,"sqlState":"42S02","sqlMessage":"Table 'test_db.users' doesn't exist","sql":"SELECT `id`, `firstname`, `lastname`, `email`, `password`, `createdAt`, `updatedAt` FROM `users` AS `user` WHERE `user`.`email` = 'mosta1996@hotmail.com';"},"original":{"code":"ER_NO_SUCH_TABLE","errno":1146,"sqlState":"42S02","sqlMessage":"Table 'test_db.users' doesn't exist","sql":"SELECT `id`, `firstname`, `lastname`, `email`, `password`, `createdAt`, `updatedAt` FROM `users` AS `user` WHERE `user`.`email` = 'mosta1996@hotmail.com';"},"sql":"SELECT `id`, `firstname`, `lastname`, `email`, `password`, `createdAt`, `updatedAt` FROM `users` AS `user` WHERE `user`.`email` = 'mosta1996@hotmail.com';","level":"\u001b[31merror\u001b[39m","message":"Table 'test_db.users' doesn't exist Table 'test_db.users' doesn't exist","stack":"SequelizeDatabaseError: Table 'test_db.users' doesn't exist\n    at Query.formatError (/server/node_modules/sequelize/lib/dialects/mysql/query.js:265:16)\n    at Query.run (/server/node_modules/sequelize/lib/dialects/mysql/query.js:77:18)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async /server/node_modules/sequelize/lib/sequelize.js:619:16\n    at async MySQLQueryInterface.select (/server/node_modules/sequelize/lib/dialects/abstract/query-interface.js:953:12)\n    at async Function.findAll (/server/node_modules/sequelize/lib/model.js:1753:21)\n    at async Function.findOne (/server/node_modules/sequelize/lib/model.js:1917:12)\n    at async UserAdapter.getOne (/server/server/adapters/mysql_database/BaseAdapter.js:40:24)\n    at async UserAdapter.getOne (/server/server/adapters/mysql_database/user.adapter.js:33:20)\n    at async UserController.getOne (/server/server/controllers/Controller.js:41:24)","timestamp":"2021-09-14T13:35:16.182Z"}
{"name":"SequelizeDatabaseError","parent":{"code":"ER_NO_SUCH_TABLE","errno":1146,"sqlState":"42S02","sqlMessage":"Table 'test_db.users' doesn't exist","sql":"SELECT `id`, `firstname`, `lastname`, `email`, `password`, `createdAt`, `updatedAt` FROM `users` AS `user` WHERE `user`.`email` = 'mosta1996@hotmail.com';"},"original":{"code":"ER_NO_SUCH_TABLE","errno":1146,"sqlState":"42S02","sqlMessage":"Table 'test_db.users' doesn't exist","sql":"SELECT `id`, `firstname`, `lastname`, `email`, `password`, `createdAt`, `updatedAt` FROM `users` AS `user` WHERE `user`.`email` = 'mosta1996@hotmail.com';"},"sql":"SELECT `id`, `firstname`, `lastname`, `email`, `password`, `createdAt`, `updatedAt` FROM `users` AS `user` WHERE `user`.`email` = 'mosta1996@hotmail.com';","level":"\u001b[31merror\u001b[39m","message":"Table 'test_db.users' doesn't exist Table 'test_db.users' doesn't exist","stack":"SequelizeDatabaseError: Table 'test_db.users' doesn't exist\n    at Query.formatError (/server/node_modules/sequelize/lib/dialects/mysql/query.js:265:16)\n    at Query.run (/server/node_modules/sequelize/lib/dialects/mysql/query.js:77:18)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async /server/node_modules/sequelize/lib/sequelize.js:619:16\n    at async MySQLQueryInterface.select (/server/node_modules/sequelize/lib/dialects/abstract/query-interface.js:953:12)\n    at async Function.findAll (/server/node_modules/sequelize/lib/model.js:1753:21)\n    at async Function.findOne (/server/node_modules/sequelize/lib/model.js:1917:12)\n    at async UserAdapter.getOne (/server/server/adapters/mysql_database/BaseAdapter.js:40:24)\n    at async UserAdapter.getOne (/server/server/adapters/mysql_database/user.adapter.js:33:20)\n    at async UserController.getOne (/server/server/controllers/Controller.js:41:24)","timestamp":"2021-09-14T13:35:16.183Z"}
{"name":"SequelizeDatabaseError","parent":{"code":"ER_NO_SUCH_TABLE","errno":1146,"sqlState":"42S02","sqlMessage":"Table 'test_db.users' doesn't exist","sql":"SELECT `id`, `firstname`, `lastname`, `email`, `password`, `createdAt`, `updatedAt` FROM `users` AS `user` WHERE `user`.`email` = 'mosta1996@hotmail.com';"},"original":{"code":"ER_NO_SUCH_TABLE","errno":1146,"sqlState":"42S02","sqlMessage":"Table 'test_db.users' doesn't exist","sql":"SELECT `id`, `firstname`, `lastname`, `email`, `password`, `createdAt`, `updatedAt` FROM `users` AS `user` WHERE `user`.`email` = 'mosta1996@hotmail.com';"},"sql":"SELECT `id`, `firstname`, `lastname`, `email`, `password`, `createdAt`, `updatedAt` FROM `users` AS `user` WHERE `user`.`email` = 'mosta1996@hotmail.com';","level":"\u001b[31merror\u001b[39m","message":"Table 'test_db.users' doesn't exist Table 'test_db.users' doesn't exist","stack":"SequelizeDatabaseError: Table 'test_db.users' doesn't exist\n    at Query.formatError (/server/node_modules/sequelize/lib/dialects/mysql/query.js:265:16)\n    at Query.run (/server/node_modules/sequelize/lib/dialects/mysql/query.js:77:18)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async /server/node_modules/sequelize/lib/sequelize.js:619:16\n    at async MySQLQueryInterface.select (/server/node_modules/sequelize/lib/dialects/abstract/query-interface.js:953:12)\n    at async Function.findAll (/server/node_modules/sequelize/lib/model.js:1753:21)\n    at async Function.findOne (/server/node_modules/sequelize/lib/model.js:1917:12)\n    at async UserAdapter.getOne (/server/server/adapters/mysql_database/BaseAdapter.js:40:24)\n    at async UserAdapter.getOne (/server/server/adapters/mysql_database/user.adapter.js:33:20)\n    at async UserController.getOne (/server/server/controllers/Controller.js:41:24)","timestamp":"2021-09-14T13:35:16.184Z"}
{"name":"SequelizeDatabaseError","parent":{"code":"ER_NO_SUCH_TABLE","errno":1146,"sqlState":"42S02","sqlMessage":"Table 'test_db.users' doesn't exist","sql":"SELECT `id`, `firstname`, `lastname`, `email`, `password`, `createdAt`, `updatedAt` FROM `users` AS `user` WHERE `user`.`email` = 'mosta1996@hotmail.com';"},"original":{"code":"ER_NO_SUCH_TABLE","errno":1146,"sqlState":"42S02","sqlMessage":"Table 'test_db.users' doesn't exist","sql":"SELECT `id`, `firstname`, `lastname`, `email`, `password`, `createdAt`, `updatedAt` FROM `users` AS `user` WHERE `user`.`email` = 'mosta1996@hotmail.com';"},"sql":"SELECT `id`, `firstname`, `lastname`, `email`, `password`, `createdAt`, `updatedAt` FROM `users` AS `user` WHERE `user`.`email` = 'mosta1996@hotmail.com';","level":"\u001b[31merror\u001b[39m","message":"Table 'test_db.users' doesn't exist Table 'test_db.users' doesn't exist","stack":"SequelizeDatabaseError: Table 'test_db.users' doesn't exist\n    at Query.formatError (/server/node_modules/sequelize/lib/dialects/mysql/query.js:265:16)\n    at Query.run (/server/node_modules/sequelize/lib/dialects/mysql/query.js:77:18)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async /server/node_modules/sequelize/lib/sequelize.js:619:16\n    at async MySQLQueryInterface.select (/server/node_modules/sequelize/lib/dialects/abstract/query-interface.js:953:12)\n    at async Function.findAll (/server/node_modules/sequelize/lib/model.js:1753:21)\n    at async Function.findOne (/server/node_modules/sequelize/lib/model.js:1917:12)\n    at async UserAdapter.getOne (/server/server/adapters/mysql_database/BaseAdapter.js:40:24)\n    at async UserAdapter.getOne (/server/server/adapters/mysql_database/user.adapter.js:33:20)\n    at async UserController.getOne (/server/server/controllers/Controller.js:41:24)","timestamp":"2021-09-14T13:35:16.184Z"}
{"name":"SequelizeDatabaseError","parent":{"code":"ER_NO_SUCH_TABLE","errno":1146,"sqlState":"42S02","sqlMessage":"Table 'test_db.users' doesn't exist","sql":"SELECT `id`, `firstname`, `lastname`, `email`, `password`, `createdAt`, `updatedAt` FROM `users` AS `user` WHERE `user`.`email` = 'mosta1996@hotmail.com';"},"original":{"code":"ER_NO_SUCH_TABLE","errno":1146,"sqlState":"42S02","sqlMessage":"Table 'test_db.users' doesn't exist","sql":"SELECT `id`, `firstname`, `lastname`, `email`, `password`, `createdAt`, `updatedAt` FROM `users` AS `user` WHERE `user`.`email` = 'mosta1996@hotmail.com';"},"sql":"SELECT `id`, `firstname`, `lastname`, `email`, `password`, `createdAt`, `updatedAt` FROM `users` AS `user` WHERE `user`.`email` = 'mosta1996@hotmail.com';","level":"\u001b[31merror\u001b[39m","message":"Table 'test_db.users' doesn't exist Table 'test_db.users' doesn't exist","stack":"SequelizeDatabaseError: Table 'test_db.users' doesn't exist\n    at Query.formatError (/server/node_modules/sequelize/lib/dialects/mysql/query.js:265:16)\n    at Query.run (/server/node_modules/sequelize/lib/dialects/mysql/query.js:77:18)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async /server/node_modules/sequelize/lib/sequelize.js:619:16\n    at async MySQLQueryInterface.select (/server/node_modules/sequelize/lib/dialects/abstract/query-interface.js:953:12)\n    at async Function.findAll (/server/node_modules/sequelize/lib/model.js:1753:21)\n    at async Function.findOne (/server/node_modules/sequelize/lib/model.js:1917:12)\n    at async UserAdapter.getOne (/server/server/adapters/mysql_database/BaseAdapter.js:40:24)\n    at async UserAdapter.getOne (/server/server/adapters/mysql_database/user.adapter.js:33:20)\n    at async UserController.getOne (/server/server/controllers/Controller.js:41:24)","timestamp":"2021-09-14T13:38:08.120Z"}
{"name":"SequelizeDatabaseError","parent":{"code":"ER_NO_SUCH_TABLE","errno":1146,"sqlState":"42S02","sqlMessage":"Table 'test_db.users' doesn't exist","sql":"SELECT `id`, `firstname`, `lastname`, `email`, `password`, `createdAt`, `updatedAt` FROM `users` AS `user` WHERE `user`.`email` = 'mosta1996@hotmail.com';"},"original":{"code":"ER_NO_SUCH_TABLE","errno":1146,"sqlState":"42S02","sqlMessage":"Table 'test_db.users' doesn't exist","sql":"SELECT `id`, `firstname`, `lastname`, `email`, `password`, `createdAt`, `updatedAt` FROM `users` AS `user` WHERE `user`.`email` = 'mosta1996@hotmail.com';"},"sql":"SELECT `id`, `firstname`, `lastname`, `email`, `password`, `createdAt`, `updatedAt` FROM `users` AS `user` WHERE `user`.`email` = 'mosta1996@hotmail.com';","level":"\u001b[31merror\u001b[39m","message":"Table 'test_db.users' doesn't exist Table 'test_db.users' doesn't exist","stack":"SequelizeDatabaseError: Table 'test_db.users' doesn't exist\n    at Query.formatError (/server/node_modules/sequelize/lib/dialects/mysql/query.js:265:16)\n    at Query.run (/server/node_modules/sequelize/lib/dialects/mysql/query.js:77:18)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async /server/node_modules/sequelize/lib/sequelize.js:619:16\n    at async MySQLQueryInterface.select (/server/node_modules/sequelize/lib/dialects/abstract/query-interface.js:953:12)\n    at async Function.findAll (/server/node_modules/sequelize/lib/model.js:1753:21)\n    at async Function.findOne (/server/node_modules/sequelize/lib/model.js:1917:12)\n    at async UserAdapter.getOne (/server/server/adapters/mysql_database/BaseAdapter.js:40:24)\n    at async UserAdapter.getOne (/server/server/adapters/mysql_database/user.adapter.js:33:20)\n    at async UserController.getOne (/server/server/controllers/Controller.js:41:24)","timestamp":"2021-09-14T13:38:08.121Z"}
{"name":"SequelizeDatabaseError","parent":{"code":"ER_NO_SUCH_TABLE","errno":1146,"sqlState":"42S02","sqlMessage":"Table 'test_db.users' doesn't exist","sql":"SELECT `id`, `firstname`, `lastname`, `email`, `password`, `createdAt`, `updatedAt` FROM `users` AS `user` WHERE `user`.`email` = 'mosta1996@hotmail.com';"},"original":{"code":"ER_NO_SUCH_TABLE","errno":1146,"sqlState":"42S02","sqlMessage":"Table 'test_db.users' doesn't exist","sql":"SELECT `id`, `firstname`, `lastname`, `email`, `password`, `createdAt`, `updatedAt` FROM `users` AS `user` WHERE `user`.`email` = 'mosta1996@hotmail.com';"},"sql":"SELECT `id`, `firstname`, `lastname`, `email`, `password`, `createdAt`, `updatedAt` FROM `users` AS `user` WHERE `user`.`email` = 'mosta1996@hotmail.com';","level":"\u001b[31merror\u001b[39m","message":"Table 'test_db.users' doesn't exist Table 'test_db.users' doesn't exist","stack":"SequelizeDatabaseError: Table 'test_db.users' doesn't exist\n    at Query.formatError (/server/node_modules/sequelize/lib/dialects/mysql/query.js:265:16)\n    at Query.run (/server/node_modules/sequelize/lib/dialects/mysql/query.js:77:18)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async /server/node_modules/sequelize/lib/sequelize.js:619:16\n    at async MySQLQueryInterface.select (/server/node_modules/sequelize/lib/dialects/abstract/query-interface.js:953:12)\n    at async Function.findAll (/server/node_modules/sequelize/lib/model.js:1753:21)\n    at async Function.findOne (/server/node_modules/sequelize/lib/model.js:1917:12)\n    at async UserAdapter.getOne (/server/server/adapters/mysql_database/BaseAdapter.js:40:24)\n    at async UserAdapter.getOne (/server/server/adapters/mysql_database/user.adapter.js:33:20)\n    at async UserController.getOne (/server/server/controllers/Controller.js:41:24)","timestamp":"2021-09-14T13:38:08.122Z"}
{"name":"SequelizeDatabaseError","parent":{"code":"ER_NO_SUCH_TABLE","errno":1146,"sqlState":"42S02","sqlMessage":"Table 'test_db.users' doesn't exist","sql":"SELECT `id`, `firstname`, `lastname`, `email`, `password`, `createdAt`, `updatedAt` FROM `users` AS `user` WHERE `user`.`email` = 'mosta1996@hotmail.com';"},"original":{"code":"ER_NO_SUCH_TABLE","errno":1146,"sqlState":"42S02","sqlMessage":"Table 'test_db.users' doesn't exist","sql":"SELECT `id`, `firstname`, `lastname`, `email`, `password`, `createdAt`, `updatedAt` FROM `users` AS `user` WHERE `user`.`email` = 'mosta1996@hotmail.com';"},"sql":"SELECT `id`, `firstname`, `lastname`, `email`, `password`, `createdAt`, `updatedAt` FROM `users` AS `user` WHERE `user`.`email` = 'mosta1996@hotmail.com';","level":"\u001b[31merror\u001b[39m","message":"Table 'test_db.users' doesn't exist Table 'test_db.users' doesn't exist","stack":"SequelizeDatabaseError: Table 'test_db.users' doesn't exist\n    at Query.formatError (/server/node_modules/sequelize/lib/dialects/mysql/query.js:265:16)\n    at Query.run (/server/node_modules/sequelize/lib/dialects/mysql/query.js:77:18)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async /server/node_modules/sequelize/lib/sequelize.js:619:16\n    at async MySQLQueryInterface.select (/server/node_modules/sequelize/lib/dialects/abstract/query-interface.js:953:12)\n    at async Function.findAll (/server/node_modules/sequelize/lib/model.js:1753:21)\n    at async Function.findOne (/server/node_modules/sequelize/lib/model.js:1917:12)\n    at async UserAdapter.getOne (/server/server/adapters/mysql_database/BaseAdapter.js:40:24)\n    at async UserAdapter.getOne (/server/server/adapters/mysql_database/user.adapter.js:33:20)\n    at async UserController.getOne (/server/server/controllers/Controller.js:41:24)","timestamp":"2021-09-14T13:38:08.122Z"}
{"statusCode":"User not found","level":"\u001b[31merror\u001b[39m","stack":"Error\n    at new BaseError (/server/errors/baseError.js:8:11)\n    at new NotFound (/server/errors/errors.js:25:5)\n    at UserAdapter.getOne (/server/server/adapters/mysql_database/user.adapter.js:34:24)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async UserController.getOne (/server/server/controllers/Controller.js:41:24)\n    at async UserController.createUser (/server/server/controllers/user.controller.js:15:18)\n    at async /server/server/routers/user.js:12:18","timestamp":"2021-09-14T13:47:49.684Z"}
{"statusCode":"User not found","level":"\u001b[31merror\u001b[39m","stack":"Error\n    at new BaseError (/server/errors/baseError.js:8:11)\n    at new NotFound (/server/errors/errors.js:25:5)\n    at UserAdapter.getOne (/server/server/adapters/mysql_database/user.adapter.js:34:24)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async UserController.getOne (/server/server/controllers/Controller.js:41:24)\n    at async UserController.createUser (/server/server/controllers/user.controller.js:15:18)\n    at async /server/server/routers/user.js:12:18","timestamp":"2021-09-14T13:47:49.686Z"}
{"statusCode":"User not found","level":"\u001b[31merror\u001b[39m","stack":"Error\n    at new BaseError (/server/errors/baseError.js:8:11)\n    at new NotFound (/server/errors/errors.js:25:5)\n    at UserAdapter.getOne (/server/server/adapters/mysql_database/user.adapter.js:34:24)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async UserController.getOne (/server/server/controllers/Controller.js:41:24)\n    at async UserController.createUser (/server/server/controllers/user.controller.js:15:18)\n    at async /server/server/routers/user.js:12:18","timestamp":"2021-09-14T13:47:49.686Z"}
{"statusCode":"User not found","level":"\u001b[31merror\u001b[39m","stack":"Error\n    at new BaseError (/server/errors/baseError.js:8:11)\n    at new NotFound (/server/errors/errors.js:25:5)\n    at UserAdapter.getOne (/server/server/adapters/mysql_database/user.adapter.js:34:24)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async UserController.getOne (/server/server/controllers/Controller.js:41:24)\n    at async UserController.createUser (/server/server/controllers/user.controller.js:15:18)\n    at async /server/server/routers/user.js:12:18","timestamp":"2021-09-14T13:48:13.351Z"}
{"statusCode":"User not found","level":"\u001b[31merror\u001b[39m","stack":"Error\n    at new BaseError (/server/errors/baseError.js:8:11)\n    at new NotFound (/server/errors/errors.js:25:5)\n    at UserAdapter.getOne (/server/server/adapters/mysql_database/user.adapter.js:34:24)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async UserController.getOne (/server/server/controllers/Controller.js:41:24)\n    at async UserController.createUser (/server/server/controllers/user.controller.js:15:18)\n    at async /server/server/routers/user.js:12:18","timestamp":"2021-09-14T13:48:13.352Z"}
{"statusCode":"User not found","level":"\u001b[31merror\u001b[39m","stack":"Error\n    at new BaseError (/server/errors/baseError.js:8:11)\n    at new NotFound (/server/errors/errors.js:25:5)\n    at UserAdapter.getOne (/server/server/adapters/mysql_database/user.adapter.js:34:24)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async UserController.getOne (/server/server/controllers/Controller.js:41:24)\n    at async UserController.createUser (/server/server/controllers/user.controller.js:15:18)\n    at async /server/server/routers/user.js:12:18","timestamp":"2021-09-14T13:48:13.353Z"}
{"name":"SequelizeValidationError","errors":[{"message":"user.id cannot be null","type":"notNull Violation","path":"id","value":null,"origin":"CORE","instance":{"id":null,"firstname":"mostafa","lastname":"moneib","email":"mosta1996@hotmail.com","password":"12345678","updatedAt":"2021-09-14T14:01:36.265Z","createdAt":"2021-09-14T14:01:36.265Z"},"validatorKey":"is_null","validatorName":null,"validatorArgs":[]},{"message":"Validation max on password failed","type":"Validation error","path":"password","value":"12345678","origin":"FUNCTION","instance":{"id":null,"firstname":"mostafa","lastname":"moneib","email":"mosta1996@hotmail.com","password":"12345678","updatedAt":"2021-09-14T14:01:36.265Z","createdAt":"2021-09-14T14:01:36.265Z"},"validatorKey":"max","validatorName":"max","validatorArgs":[12],"original":{"validatorName":"max","validatorArgs":[12]}}],"level":"\u001b[31merror\u001b[39m","message":"notNull Violation: user.id cannot be null,\nValidation error: Validation max on password failed notNull Violation: user.id cannot be null,\nValidation error: Validation max on password failed","stack":"SequelizeValidationError: notNull Violation: user.id cannot be null,\nValidation error: Validation max on password failed\n    at InstanceValidator._validate (/server/node_modules/sequelize/lib/instance-validator.js:78:13)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async InstanceValidator._validateAndRunHooks (/server/node_modules/sequelize/lib/instance-validator.js:111:7)\n    at async InstanceValidator.validate (/server/node_modules/sequelize/lib/instance-validator.js:93:12)\n    at async model.save (/server/node_modules/sequelize/lib/model.js:3890:7)\n    at async Function.create (/server/node_modules/sequelize/lib/model.js:2207:12)\n    at async UserAdapter.create (/server/server/adapters/mysql_database/BaseAdapter.js:18:24)\n    at async UserAdapter.create (/server/server/adapters/mysql_database/user.adapter.js:14:20)\n    at async UserController.create (/server/server/controllers/Controller.js:23:24)\n    at async UserController.createUser (/server/server/controllers/user.controller.js:17:14)","timestamp":"2021-09-14T14:01:36.270Z"}
{"name":"SequelizeValidationError","errors":[{"message":"user.id cannot be null","type":"notNull Violation","path":"id","value":null,"origin":"CORE","instance":{"id":null,"firstname":"mostafa","lastname":"moneib","email":"mosta1996@hotmail.com","password":"12345678","updatedAt":"2021-09-14T14:01:36.265Z","createdAt":"2021-09-14T14:01:36.265Z"},"validatorKey":"is_null","validatorName":null,"validatorArgs":[]},{"message":"Validation max on password failed","type":"Validation error","path":"password","value":"12345678","origin":"FUNCTION","instance":{"id":null,"firstname":"mostafa","lastname":"moneib","email":"mosta1996@hotmail.com","password":"12345678","updatedAt":"2021-09-14T14:01:36.265Z","createdAt":"2021-09-14T14:01:36.265Z"},"validatorKey":"max","validatorName":"max","validatorArgs":[12],"original":{"validatorName":"max","validatorArgs":[12]}}],"level":"\u001b[31merror\u001b[39m","message":"notNull Violation: user.id cannot be null,\nValidation error: Validation max on password failed notNull Violation: user.id cannot be null,\nValidation error: Validation max on password failed","stack":"SequelizeValidationError: notNull Violation: user.id cannot be null,\nValidation error: Validation max on password failed\n    at InstanceValidator._validate (/server/node_modules/sequelize/lib/instance-validator.js:78:13)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async InstanceValidator._validateAndRunHooks (/server/node_modules/sequelize/lib/instance-validator.js:111:7)\n    at async InstanceValidator.validate (/server/node_modules/sequelize/lib/instance-validator.js:93:12)\n    at async model.save (/server/node_modules/sequelize/lib/model.js:3890:7)\n    at async Function.create (/server/node_modules/sequelize/lib/model.js:2207:12)\n    at async UserAdapter.create (/server/server/adapters/mysql_database/BaseAdapter.js:18:24)\n    at async UserAdapter.create (/server/server/adapters/mysql_database/user.adapter.js:14:20)\n    at async UserController.create (/server/server/controllers/Controller.js:23:24)\n    at async UserController.createUser (/server/server/controllers/user.controller.js:17:14)","timestamp":"2021-09-14T14:01:36.271Z"}
{"name":"SequelizeValidationError","errors":[{"message":"user.id cannot be null","type":"notNull Violation","path":"id","value":null,"origin":"CORE","instance":{"id":null,"firstname":"mostafa","lastname":"moneib","email":"mosta1996@hotmail.com","password":"12345678","updatedAt":"2021-09-14T14:01:36.265Z","createdAt":"2021-09-14T14:01:36.265Z"},"validatorKey":"is_null","validatorName":null,"validatorArgs":[]},{"message":"Validation max on password failed","type":"Validation error","path":"password","value":"12345678","origin":"FUNCTION","instance":{"id":null,"firstname":"mostafa","lastname":"moneib","email":"mosta1996@hotmail.com","password":"12345678","updatedAt":"2021-09-14T14:01:36.265Z","createdAt":"2021-09-14T14:01:36.265Z"},"validatorKey":"max","validatorName":"max","validatorArgs":[12],"original":{"validatorName":"max","validatorArgs":[12]}}],"level":"\u001b[31merror\u001b[39m","message":"notNull Violation: user.id cannot be null,\nValidation error: Validation max on password failed notNull Violation: user.id cannot be null,\nValidation error: Validation max on password failed","stack":"SequelizeValidationError: notNull Violation: user.id cannot be null,\nValidation error: Validation max on password failed\n    at InstanceValidator._validate (/server/node_modules/sequelize/lib/instance-validator.js:78:13)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async InstanceValidator._validateAndRunHooks (/server/node_modules/sequelize/lib/instance-validator.js:111:7)\n    at async InstanceValidator.validate (/server/node_modules/sequelize/lib/instance-validator.js:93:12)\n    at async model.save (/server/node_modules/sequelize/lib/model.js:3890:7)\n    at async Function.create (/server/node_modules/sequelize/lib/model.js:2207:12)\n    at async UserAdapter.create (/server/server/adapters/mysql_database/BaseAdapter.js:18:24)\n    at async UserAdapter.create (/server/server/adapters/mysql_database/user.adapter.js:14:20)\n    at async UserController.create (/server/server/controllers/Controller.js:23:24)\n    at async UserController.createUser (/server/server/controllers/user.controller.js:17:14)","timestamp":"2021-09-14T14:01:36.274Z"}
{"name":"SequelizeValidationError","errors":[{"message":"user.id cannot be null","type":"notNull Violation","path":"id","value":null,"origin":"CORE","instance":{"id":null,"firstname":"mostafa","lastname":"moneib","email":"mosta1996@hotmail.com","password":"12345678","updatedAt":"2021-09-14T14:01:36.265Z","createdAt":"2021-09-14T14:01:36.265Z"},"validatorKey":"is_null","validatorName":null,"validatorArgs":[]},{"message":"Validation max on password failed","type":"Validation error","path":"password","value":"12345678","origin":"FUNCTION","instance":{"id":null,"firstname":"mostafa","lastname":"moneib","email":"mosta1996@hotmail.com","password":"12345678","updatedAt":"2021-09-14T14:01:36.265Z","createdAt":"2021-09-14T14:01:36.265Z"},"validatorKey":"max","validatorName":"max","validatorArgs":[12],"original":{"validatorName":"max","validatorArgs":[12]}}],"level":"\u001b[31merror\u001b[39m","message":"notNull Violation: user.id cannot be null,\nValidation error: Validation max on password failed notNull Violation: user.id cannot be null,\nValidation error: Validation max on password failed","stack":"SequelizeValidationError: notNull Violation: user.id cannot be null,\nValidation error: Validation max on password failed\n    at InstanceValidator._validate (/server/node_modules/sequelize/lib/instance-validator.js:78:13)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async InstanceValidator._validateAndRunHooks (/server/node_modules/sequelize/lib/instance-validator.js:111:7)\n    at async InstanceValidator.validate (/server/node_modules/sequelize/lib/instance-validator.js:93:12)\n    at async model.save (/server/node_modules/sequelize/lib/model.js:3890:7)\n    at async Function.create (/server/node_modules/sequelize/lib/model.js:2207:12)\n    at async UserAdapter.create (/server/server/adapters/mysql_database/BaseAdapter.js:18:24)\n    at async UserAdapter.create (/server/server/adapters/mysql_database/user.adapter.js:14:20)\n    at async UserController.create (/server/server/controllers/Controller.js:23:24)\n    at async UserController.createUser (/server/server/controllers/user.controller.js:17:14)","timestamp":"2021-09-14T14:01:36.275Z"}
{"name":"SequelizeValidationError","errors":[{"message":"user.id cannot be null","type":"notNull Violation","path":"id","value":null,"origin":"CORE","instance":{"id":null,"firstname":"mostafa","lastname":"moneib","email":"mosta1996@hotmail.com","password":"12345678","updatedAt":"2021-09-14T14:02:11.382Z","createdAt":"2021-09-14T14:02:11.382Z"},"validatorKey":"is_null","validatorName":null,"validatorArgs":[]},{"message":"Validation max on password failed","type":"Validation error","path":"password","value":"12345678","origin":"FUNCTION","instance":{"id":null,"firstname":"mostafa","lastname":"moneib","email":"mosta1996@hotmail.com","password":"12345678","updatedAt":"2021-09-14T14:02:11.382Z","createdAt":"2021-09-14T14:02:11.382Z"},"validatorKey":"max","validatorName":"max","validatorArgs":[12],"original":{"validatorName":"max","validatorArgs":[12]}}],"level":"\u001b[31merror\u001b[39m","message":"notNull Violation: user.id cannot be null,\nValidation error: Validation max on password failed notNull Violation: user.id cannot be null,\nValidation error: Validation max on password failed","stack":"SequelizeValidationError: notNull Violation: user.id cannot be null,\nValidation error: Validation max on password failed\n    at InstanceValidator._validate (/server/node_modules/sequelize/lib/instance-validator.js:78:13)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async InstanceValidator._validateAndRunHooks (/server/node_modules/sequelize/lib/instance-validator.js:111:7)\n    at async InstanceValidator.validate (/server/node_modules/sequelize/lib/instance-validator.js:93:12)\n    at async model.save (/server/node_modules/sequelize/lib/model.js:3890:7)\n    at async Function.create (/server/node_modules/sequelize/lib/model.js:2207:12)\n    at async UserAdapter.create (/server/server/adapters/mysql_database/BaseAdapter.js:18:24)\n    at async UserAdapter.create (/server/server/adapters/mysql_database/user.adapter.js:14:20)\n    at async UserController.create (/server/server/controllers/Controller.js:23:24)\n    at async UserController.createUser (/server/server/controllers/user.controller.js:17:14)","timestamp":"2021-09-14T14:02:11.383Z"}
{"name":"SequelizeValidationError","errors":[{"message":"user.id cannot be null","type":"notNull Violation","path":"id","value":null,"origin":"CORE","instance":{"id":null,"firstname":"mostafa","lastname":"moneib","email":"mosta1996@hotmail.com","password":"12345678","updatedAt":"2021-09-14T14:02:11.382Z","createdAt":"2021-09-14T14:02:11.382Z"},"validatorKey":"is_null","validatorName":null,"validatorArgs":[]},{"message":"Validation max on password failed","type":"Validation error","path":"password","value":"12345678","origin":"FUNCTION","instance":{"id":null,"firstname":"mostafa","lastname":"moneib","email":"mosta1996@hotmail.com","password":"12345678","updatedAt":"2021-09-14T14:02:11.382Z","createdAt":"2021-09-14T14:02:11.382Z"},"validatorKey":"max","validatorName":"max","validatorArgs":[12],"original":{"validatorName":"max","validatorArgs":[12]}}],"level":"\u001b[31merror\u001b[39m","message":"notNull Violation: user.id cannot be null,\nValidation error: Validation max on password failed notNull Violation: user.id cannot be null,\nValidation error: Validation max on password failed","stack":"SequelizeValidationError: notNull Violation: user.id cannot be null,\nValidation error: Validation max on password failed\n    at InstanceValidator._validate (/server/node_modules/sequelize/lib/instance-validator.js:78:13)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async InstanceValidator._validateAndRunHooks (/server/node_modules/sequelize/lib/instance-validator.js:111:7)\n    at async InstanceValidator.validate (/server/node_modules/sequelize/lib/instance-validator.js:93:12)\n    at async model.save (/server/node_modules/sequelize/lib/model.js:3890:7)\n    at async Function.create (/server/node_modules/sequelize/lib/model.js:2207:12)\n    at async UserAdapter.create (/server/server/adapters/mysql_database/BaseAdapter.js:18:24)\n    at async UserAdapter.create (/server/server/adapters/mysql_database/user.adapter.js:14:20)\n    at async UserController.create (/server/server/controllers/Controller.js:23:24)\n    at async UserController.createUser (/server/server/controllers/user.controller.js:17:14)","timestamp":"2021-09-14T14:02:11.385Z"}
{"name":"SequelizeValidationError","errors":[{"message":"user.id cannot be null","type":"notNull Violation","path":"id","value":null,"origin":"CORE","instance":{"id":null,"firstname":"mostafa","lastname":"moneib","email":"mosta1996@hotmail.com","password":"12345678","updatedAt":"2021-09-14T14:02:11.382Z","createdAt":"2021-09-14T14:02:11.382Z"},"validatorKey":"is_null","validatorName":null,"validatorArgs":[]},{"message":"Validation max on password failed","type":"Validation error","path":"password","value":"12345678","origin":"FUNCTION","instance":{"id":null,"firstname":"mostafa","lastname":"moneib","email":"mosta1996@hotmail.com","password":"12345678","updatedAt":"2021-09-14T14:02:11.382Z","createdAt":"2021-09-14T14:02:11.382Z"},"validatorKey":"max","validatorName":"max","validatorArgs":[12],"original":{"validatorName":"max","validatorArgs":[12]}}],"level":"\u001b[31merror\u001b[39m","message":"notNull Violation: user.id cannot be null,\nValidation error: Validation max on password failed notNull Violation: user.id cannot be null,\nValidation error: Validation max on password failed","stack":"SequelizeValidationError: notNull Violation: user.id cannot be null,\nValidation error: Validation max on password failed\n    at InstanceValidator._validate (/server/node_modules/sequelize/lib/instance-validator.js:78:13)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async InstanceValidator._validateAndRunHooks (/server/node_modules/sequelize/lib/instance-validator.js:111:7)\n    at async InstanceValidator.validate (/server/node_modules/sequelize/lib/instance-validator.js:93:12)\n    at async model.save (/server/node_modules/sequelize/lib/model.js:3890:7)\n    at async Function.create (/server/node_modules/sequelize/lib/model.js:2207:12)\n    at async UserAdapter.create (/server/server/adapters/mysql_database/BaseAdapter.js:18:24)\n    at async UserAdapter.create (/server/server/adapters/mysql_database/user.adapter.js:14:20)\n    at async UserController.create (/server/server/controllers/Controller.js:23:24)\n    at async UserController.createUser (/server/server/controllers/user.controller.js:17:14)","timestamp":"2021-09-14T14:02:11.387Z"}
{"name":"SequelizeValidationError","errors":[{"message":"user.id cannot be null","type":"notNull Violation","path":"id","value":null,"origin":"CORE","instance":{"id":null,"firstname":"mostafa","lastname":"moneib","email":"mosta1996@hotmail.com","password":"12345678","updatedAt":"2021-09-14T14:02:11.382Z","createdAt":"2021-09-14T14:02:11.382Z"},"validatorKey":"is_null","validatorName":null,"validatorArgs":[]},{"message":"Validation max on password failed","type":"Validation error","path":"password","value":"12345678","origin":"FUNCTION","instance":{"id":null,"firstname":"mostafa","lastname":"moneib","email":"mosta1996@hotmail.com","password":"12345678","updatedAt":"2021-09-14T14:02:11.382Z","createdAt":"2021-09-14T14:02:11.382Z"},"validatorKey":"max","validatorName":"max","validatorArgs":[12],"original":{"validatorName":"max","validatorArgs":[12]}}],"level":"\u001b[31merror\u001b[39m","message":"notNull Violation: user.id cannot be null,\nValidation error: Validation max on password failed notNull Violation: user.id cannot be null,\nValidation error: Validation max on password failed","stack":"SequelizeValidationError: notNull Violation: user.id cannot be null,\nValidation error: Validation max on password failed\n    at InstanceValidator._validate (/server/node_modules/sequelize/lib/instance-validator.js:78:13)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async InstanceValidator._validateAndRunHooks (/server/node_modules/sequelize/lib/instance-validator.js:111:7)\n    at async InstanceValidator.validate (/server/node_modules/sequelize/lib/instance-validator.js:93:12)\n    at async model.save (/server/node_modules/sequelize/lib/model.js:3890:7)\n    at async Function.create (/server/node_modules/sequelize/lib/model.js:2207:12)\n    at async UserAdapter.create (/server/server/adapters/mysql_database/BaseAdapter.js:18:24)\n    at async UserAdapter.create (/server/server/adapters/mysql_database/user.adapter.js:14:20)\n    at async UserController.create (/server/server/controllers/Controller.js:23:24)\n    at async UserController.createUser (/server/server/controllers/user.controller.js:17:14)","timestamp":"2021-09-14T14:02:11.388Z"}
{"name":"SequelizeValidationError","errors":[{"message":"Validation max on password failed","type":"Validation error","path":"password","value":"12345678","origin":"FUNCTION","instance":{"id":"cdc1c931-a8f6-4b3b-a237-f24ea8b5975c","firstname":"mostafa","lastname":"moneib","email":"mosta1996@hotmail.com","password":"12345678","updatedAt":"2021-09-14T14:03:23.501Z","createdAt":"2021-09-14T14:03:23.501Z"},"validatorKey":"max","validatorName":"max","validatorArgs":[12],"original":{"validatorName":"max","validatorArgs":[12]}}],"level":"\u001b[31merror\u001b[39m","message":"Validation error: Validation max on password failed Validation error: Validation max on password failed","stack":"SequelizeValidationError: Validation error: Validation max on password failed\n    at InstanceValidator._validate (/server/node_modules/sequelize/lib/instance-validator.js:78:13)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async InstanceValidator._validateAndRunHooks (/server/node_modules/sequelize/lib/instance-validator.js:111:7)\n    at async InstanceValidator.validate (/server/node_modules/sequelize/lib/instance-validator.js:93:12)\n    at async model.save (/server/node_modules/sequelize/lib/model.js:3890:7)\n    at async Function.create (/server/node_modules/sequelize/lib/model.js:2207:12)\n    at async UserAdapter.create (/server/server/adapters/mysql_database/BaseAdapter.js:18:24)\n    at async UserAdapter.create (/server/server/adapters/mysql_database/user.adapter.js:14:20)\n    at async UserController.create (/server/server/controllers/Controller.js:23:24)\n    at async UserController.createUser (/server/server/controllers/user.controller.js:17:14)","timestamp":"2021-09-14T14:03:23.506Z"}
{"name":"SequelizeValidationError","errors":[{"message":"Validation max on password failed","type":"Validation error","path":"password","value":"12345678","origin":"FUNCTION","instance":{"id":"cdc1c931-a8f6-4b3b-a237-f24ea8b5975c","firstname":"mostafa","lastname":"moneib","email":"mosta1996@hotmail.com","password":"12345678","updatedAt":"2021-09-14T14:03:23.501Z","createdAt":"2021-09-14T14:03:23.501Z"},"validatorKey":"max","validatorName":"max","validatorArgs":[12],"original":{"validatorName":"max","validatorArgs":[12]}}],"level":"\u001b[31merror\u001b[39m","message":"Validation error: Validation max on password failed Validation error: Validation max on password failed","stack":"SequelizeValidationError: Validation error: Validation max on password failed\n    at InstanceValidator._validate (/server/node_modules/sequelize/lib/instance-validator.js:78:13)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async InstanceValidator._validateAndRunHooks (/server/node_modules/sequelize/lib/instance-validator.js:111:7)\n    at async InstanceValidator.validate (/server/node_modules/sequelize/lib/instance-validator.js:93:12)\n    at async model.save (/server/node_modules/sequelize/lib/model.js:3890:7)\n    at async Function.create (/server/node_modules/sequelize/lib/model.js:2207:12)\n    at async UserAdapter.create (/server/server/adapters/mysql_database/BaseAdapter.js:18:24)\n    at async UserAdapter.create (/server/server/adapters/mysql_database/user.adapter.js:14:20)\n    at async UserController.create (/server/server/controllers/Controller.js:23:24)\n    at async UserController.createUser (/server/server/controllers/user.controller.js:17:14)","timestamp":"2021-09-14T14:03:23.507Z"}
{"name":"SequelizeValidationError","errors":[{"message":"Validation max on password failed","type":"Validation error","path":"password","value":"12345678","origin":"FUNCTION","instance":{"id":"cdc1c931-a8f6-4b3b-a237-f24ea8b5975c","firstname":"mostafa","lastname":"moneib","email":"mosta1996@hotmail.com","password":"12345678","updatedAt":"2021-09-14T14:03:23.501Z","createdAt":"2021-09-14T14:03:23.501Z"},"validatorKey":"max","validatorName":"max","validatorArgs":[12],"original":{"validatorName":"max","validatorArgs":[12]}}],"level":"\u001b[31merror\u001b[39m","message":"Validation error: Validation max on password failed Validation error: Validation max on password failed","stack":"SequelizeValidationError: Validation error: Validation max on password failed\n    at InstanceValidator._validate (/server/node_modules/sequelize/lib/instance-validator.js:78:13)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async InstanceValidator._validateAndRunHooks (/server/node_modules/sequelize/lib/instance-validator.js:111:7)\n    at async InstanceValidator.validate (/server/node_modules/sequelize/lib/instance-validator.js:93:12)\n    at async model.save (/server/node_modules/sequelize/lib/model.js:3890:7)\n    at async Function.create (/server/node_modules/sequelize/lib/model.js:2207:12)\n    at async UserAdapter.create (/server/server/adapters/mysql_database/BaseAdapter.js:18:24)\n    at async UserAdapter.create (/server/server/adapters/mysql_database/user.adapter.js:14:20)\n    at async UserController.create (/server/server/controllers/Controller.js:23:24)\n    at async UserController.createUser (/server/server/controllers/user.controller.js:17:14)","timestamp":"2021-09-14T14:03:23.508Z"}
{"name":"SequelizeValidationError","errors":[{"message":"Validation max on password failed","type":"Validation error","path":"password","value":"12345678","origin":"FUNCTION","instance":{"id":"cdc1c931-a8f6-4b3b-a237-f24ea8b5975c","firstname":"mostafa","lastname":"moneib","email":"mosta1996@hotmail.com","password":"12345678","updatedAt":"2021-09-14T14:03:23.501Z","createdAt":"2021-09-14T14:03:23.501Z"},"validatorKey":"max","validatorName":"max","validatorArgs":[12],"original":{"validatorName":"max","validatorArgs":[12]}}],"level":"\u001b[31merror\u001b[39m","message":"Validation error: Validation max on password failed Validation error: Validation max on password failed","stack":"SequelizeValidationError: Validation error: Validation max on password failed\n    at InstanceValidator._validate (/server/node_modules/sequelize/lib/instance-validator.js:78:13)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async InstanceValidator._validateAndRunHooks (/server/node_modules/sequelize/lib/instance-validator.js:111:7)\n    at async InstanceValidator.validate (/server/node_modules/sequelize/lib/instance-validator.js:93:12)\n    at async model.save (/server/node_modules/sequelize/lib/model.js:3890:7)\n    at async Function.create (/server/node_modules/sequelize/lib/model.js:2207:12)\n    at async UserAdapter.create (/server/server/adapters/mysql_database/BaseAdapter.js:18:24)\n    at async UserAdapter.create (/server/server/adapters/mysql_database/user.adapter.js:14:20)\n    at async UserController.create (/server/server/controllers/Controller.js:23:24)\n    at async UserController.createUser (/server/server/controllers/user.controller.js:17:14)","timestamp":"2021-09-14T14:03:23.509Z"}
{"name":"SequelizeValidationError","errors":[{"message":"Validation max on password failed","type":"Validation error","path":"password","value":"12345678","origin":"FUNCTION","instance":{"id":"223990ea-3ffe-47ae-93c6-99e36c20117b","firstname":"mostafa","lastname":"moneib","email":"mosta1996@hotmail.com","password":"12345678","updatedAt":"2021-09-14T14:07:11.052Z","createdAt":"2021-09-14T14:07:11.052Z"},"validatorKey":"max","validatorName":"max","validatorArgs":[12],"original":{"validatorName":"max","validatorArgs":[12]}}],"level":"\u001b[31merror\u001b[39m","message":"Validation error: Validation max on password failed Validation error: Validation max on password failed","stack":"SequelizeValidationError: Validation error: Validation max on password failed\n    at InstanceValidator._validate (/server/node_modules/sequelize/lib/instance-validator.js:78:13)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async InstanceValidator._validateAndRunHooks (/server/node_modules/sequelize/lib/instance-validator.js:111:7)\n    at async InstanceValidator.validate (/server/node_modules/sequelize/lib/instance-validator.js:93:12)\n    at async model.save (/server/node_modules/sequelize/lib/model.js:3890:7)\n    at async Function.create (/server/node_modules/sequelize/lib/model.js:2207:12)\n    at async UserAdapter.create (/server/server/adapters/mysql_database/BaseAdapter.js:18:24)\n    at async UserAdapter.create (/server/server/adapters/mysql_database/user.adapter.js:14:20)\n    at async UserController.create (/server/server/controllers/Controller.js:23:24)\n    at async UserController.createUser (/server/server/controllers/user.controller.js:17:14)","timestamp":"2021-09-14T14:07:11.057Z"}
{"name":"SequelizeValidationError","errors":[{"message":"Validation max on password failed","type":"Validation error","path":"password","value":"12345678","origin":"FUNCTION","instance":{"id":"223990ea-3ffe-47ae-93c6-99e36c20117b","firstname":"mostafa","lastname":"moneib","email":"mosta1996@hotmail.com","password":"12345678","updatedAt":"2021-09-14T14:07:11.052Z","createdAt":"2021-09-14T14:07:11.052Z"},"validatorKey":"max","validatorName":"max","validatorArgs":[12],"original":{"validatorName":"max","validatorArgs":[12]}}],"level":"\u001b[31merror\u001b[39m","message":"Validation error: Validation max on password failed Validation error: Validation max on password failed","stack":"SequelizeValidationError: Validation error: Validation max on password failed\n    at InstanceValidator._validate (/server/node_modules/sequelize/lib/instance-validator.js:78:13)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async InstanceValidator._validateAndRunHooks (/server/node_modules/sequelize/lib/instance-validator.js:111:7)\n    at async InstanceValidator.validate (/server/node_modules/sequelize/lib/instance-validator.js:93:12)\n    at async model.save (/server/node_modules/sequelize/lib/model.js:3890:7)\n    at async Function.create (/server/node_modules/sequelize/lib/model.js:2207:12)\n    at async UserAdapter.create (/server/server/adapters/mysql_database/BaseAdapter.js:18:24)\n    at async UserAdapter.create (/server/server/adapters/mysql_database/user.adapter.js:14:20)\n    at async UserController.create (/server/server/controllers/Controller.js:23:24)\n    at async UserController.createUser (/server/server/controllers/user.controller.js:17:14)","timestamp":"2021-09-14T14:07:11.058Z"}
{"name":"SequelizeValidationError","errors":[{"message":"Validation max on password failed","type":"Validation error","path":"password","value":"12345678","origin":"FUNCTION","instance":{"id":"223990ea-3ffe-47ae-93c6-99e36c20117b","firstname":"mostafa","lastname":"moneib","email":"mosta1996@hotmail.com","password":"12345678","updatedAt":"2021-09-14T14:07:11.052Z","createdAt":"2021-09-14T14:07:11.052Z"},"validatorKey":"max","validatorName":"max","validatorArgs":[12],"original":{"validatorName":"max","validatorArgs":[12]}}],"level":"\u001b[31merror\u001b[39m","message":"Validation error: Validation max on password failed Validation error: Validation max on password failed","stack":"SequelizeValidationError: Validation error: Validation max on password failed\n    at InstanceValidator._validate (/server/node_modules/sequelize/lib/instance-validator.js:78:13)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async InstanceValidator._validateAndRunHooks (/server/node_modules/sequelize/lib/instance-validator.js:111:7)\n    at async InstanceValidator.validate (/server/node_modules/sequelize/lib/instance-validator.js:93:12)\n    at async model.save (/server/node_modules/sequelize/lib/model.js:3890:7)\n    at async Function.create (/server/node_modules/sequelize/lib/model.js:2207:12)\n    at async UserAdapter.create (/server/server/adapters/mysql_database/BaseAdapter.js:18:24)\n    at async UserAdapter.create (/server/server/adapters/mysql_database/user.adapter.js:14:20)\n    at async UserController.create (/server/server/controllers/Controller.js:23:24)\n    at async UserController.createUser (/server/server/controllers/user.controller.js:17:14)","timestamp":"2021-09-14T14:07:11.058Z"}
{"name":"SequelizeValidationError","errors":[{"message":"Validation max on password failed","type":"Validation error","path":"password","value":"12345678","origin":"FUNCTION","instance":{"id":"223990ea-3ffe-47ae-93c6-99e36c20117b","firstname":"mostafa","lastname":"moneib","email":"mosta1996@hotmail.com","password":"12345678","updatedAt":"2021-09-14T14:07:11.052Z","createdAt":"2021-09-14T14:07:11.052Z"},"validatorKey":"max","validatorName":"max","validatorArgs":[12],"original":{"validatorName":"max","validatorArgs":[12]}}],"level":"\u001b[31merror\u001b[39m","message":"Validation error: Validation max on password failed Validation error: Validation max on password failed","stack":"SequelizeValidationError: Validation error: Validation max on password failed\n    at InstanceValidator._validate (/server/node_modules/sequelize/lib/instance-validator.js:78:13)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async InstanceValidator._validateAndRunHooks (/server/node_modules/sequelize/lib/instance-validator.js:111:7)\n    at async InstanceValidator.validate (/server/node_modules/sequelize/lib/instance-validator.js:93:12)\n    at async model.save (/server/node_modules/sequelize/lib/model.js:3890:7)\n    at async Function.create (/server/node_modules/sequelize/lib/model.js:2207:12)\n    at async UserAdapter.create (/server/server/adapters/mysql_database/BaseAdapter.js:18:24)\n    at async UserAdapter.create (/server/server/adapters/mysql_database/user.adapter.js:14:20)\n    at async UserController.create (/server/server/controllers/Controller.js:23:24)\n    at async UserController.createUser (/server/server/controllers/user.controller.js:17:14)","timestamp":"2021-09-14T14:07:11.060Z"}
{"statusCode":"user already exists","level":"\u001b[31merror\u001b[39m","stack":"Error\n    at new BaseError (/server/errors/baseError.js:8:11)\n    at new Conflict (/server/errors/errors.js:31:5)\n    at UserController.createUser (/server/server/controllers/user.controller.js:16:23)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async /server/server/routers/user.js:12:18","timestamp":"2021-09-14T14:12:59.998Z"}
{"statusCode":"user already exists","level":"\u001b[31merror\u001b[39m","stack":"Error\n    at new BaseError (/server/errors/baseError.js:8:11)\n    at new Conflict (/server/errors/errors.js:31:5)\n    at UserController.createUser (/server/server/controllers/user.controller.js:16:23)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async /server/server/routers/user.js:12:18","timestamp":"2021-09-14T14:15:37.063Z"}
{"statusCode":"user already exists","level":"\u001b[31merror\u001b[39m","stack":"Error\n    at new BaseError (/server/errors/baseError.js:8:11)\n    at new Conflict (/server/errors/errors.js:31:5)\n    at UserController.createUser (/server/server/controllers/user.controller.js:16:23)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async /server/server/routers/user.js:12:18","timestamp":"2021-09-14T14:16:27.604Z"}
{"statusCode":"user already exists","level":"\u001b[31merror\u001b[39m","timestamp":"2021-09-14T14:22:23.754Z"}
{"statusCode":"user already exists","level":"\u001b[31merror\u001b[39m","stack":"Error\n    at new BaseError (/server/errors/baseError.js:8:11)\n    at new Conflict (/server/errors/errors.js:31:5)\n    at UserController.createUser (/server/server/controllers/user.controller.js:16:23)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async /server/server/routers/user.js:12:18","timestamp":"2021-09-14T14:22:48.786Z"}
{"statusCode":"user already exists","level":"\u001b[31merror\u001b[39m","stack":"Error\n    at new BaseError (/server/errors/baseError.js:11:11)\n    at new Conflict (/server/errors/errors.js:31:5)\n    at UserController.createUser (/server/server/controllers/user.controller.js:16:23)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async /server/server/routers/user.js:12:18","timestamp":"2021-09-14T14:23:53.503Z"}
{"statusCode":"user already exists","level":"\u001b[31merror\u001b[39m","stack":"Error\n    at new BaseError (/server/errors/baseError.js:11:11)\n    at new Conflict (/server/errors/errors.js:36:5)\n    at UserController.createUser (/server/server/controllers/user.controller.js:16:23)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async /server/server/routers/user.js:12:18","timestamp":"2021-09-14T14:25:14.758Z"}
{"message":"user already exists","statusCode":409,"level":"\u001b[31merror\u001b[39m","stack":"Error: user already exists\n    at new BaseError (/server/errors/baseError.js:8:11)\n    at new Conflict (/server/errors/errors.js:31:5)\n    at UserController.createUser (/server/server/controllers/user.controller.js:16:23)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async /server/server/routers/user.js:12:18","timestamp":"2021-09-14T14:27:44.731Z"}
{"message":"user already exists","statusCode":409,"level":"\u001b[31merror\u001b[39m","stack":"Error: user already exists\n    at new BaseError (/server/errors/baseError.js:8:11)\n    at new Conflict (/server/errors/errors.js:31:5)\n    at UserController.createUser (/server/server/controllers/user.controller.js:16:23)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async /server/server/routers/user.js:12:18","timestamp":"2021-09-14T14:30:01.692Z"}
{"message":"user already exists","statusCode":409,"level":"\u001b[31merror\u001b[39m","stack":"Error: user already exists\n    at new BaseError (/server/errors/baseError.js:8:11)\n    at new Conflict (/server/errors/errors.js:31:5)\n    at UserController.createUser (/server/server/controllers/user.controller.js:16:23)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async /server/server/routers/user.js:12:18","timestamp":"2021-09-14T14:58:07.371Z"}
{"message":"user already exists","statusCode":409,"level":"\u001b[31merror\u001b[39m","stack":"Error: user already exists\n    at new BaseError (/server/errors/baseError.js:8:11)\n    at new Conflict (/server/errors/errors.js:31:5)\n    at UserController.createUser (/server/server/controllers/user.controller.js:16:23)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async /server/server/routers/user.js:12:18","timestamp":"2021-09-14T14:59:52.857Z"}
{"message":"user already exists","statusCode":409,"level":"\u001b[31merror\u001b[39m","stack":"Error: user already exists\n    at new BaseError (/server/errors/baseError.js:8:11)\n    at new Conflict (/server/errors/errors.js:31:5)\n    at UserController.createUser (/server/server/controllers/user.controller.js:16:23)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async /server/server/routers/user.js:12:18","timestamp":"2021-09-14T15:00:21.587Z"}
{"message":"user already exists","statusCode":409,"level":"\u001b[31merror\u001b[39m","stack":"Error: user already exists\n    at new BaseError (/server/errors/baseError.js:8:11)\n    at new Conflict (/server/errors/errors.js:31:5)\n    at UserController.createUser (/server/server/controllers/user.controller.js:16:23)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async /server/server/routers/user.js:12:18","timestamp":"2021-09-14T15:00:54.753Z"}
{"message":"user already exists","statusCode":409,"level":"\u001b[31merror\u001b[39m","stack":"Error: user already exists\n    at new BaseError (/server/errors/baseError.js:8:11)\n    at new Conflict (/server/errors/errors.js:31:5)\n    at UserController.createUser (/server/server/controllers/user.controller.js:16:23)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async /server/server/routers/user.js:12:18","timestamp":"2021-09-14T15:02:23.904Z"}
{"message":"user already exists","statusCode":409,"level":"\u001b[31merror\u001b[39m","stack":"Error: user already exists\n    at new BaseError (/server/errors/baseError.js:8:11)\n    at new Conflict (/server/errors/errors.js:31:5)\n    at UserController.createUser (/server/server/controllers/user.controller.js:16:23)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async /server/server/routers/user.js:12:18","timestamp":"2021-09-14T15:03:09.735Z"}
{"message":"user already exists","statusCode":409,"level":"\u001b[31merror\u001b[39m","stack":"Error: user already exists\n    at new BaseError (/server/errors/baseError.js:8:11)\n    at new Conflict (/server/errors/errors.js:31:5)\n    at UserController.createUser (/server/server/controllers/user.controller.js:16:23)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async /server/server/routers/user.js:12:18","timestamp":"2021-09-14T15:08:57.460Z"}
{"message":"user already exists","statusCode":409,"level":"\u001b[31merror\u001b[39m","stack":"Error: user already exists\n    at new BaseError (/server/errors/baseError.js:8:11)\n    at new Conflict (/server/errors/errors.js:31:5)\n    at UserController.createUser (/server/server/controllers/user.controller.js:16:23)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async /server/server/routers/user.js:12:18","timestamp":"2021-09-14T15:09:58.643Z"}
{"message":"user already exists","statusCode":409,"level":"\u001b[31merror\u001b[39m","stack":"Error: user already exists\n    at new BaseError (/server/errors/baseError.js:8:11)\n    at new Conflict (/server/errors/errors.js:31:5)\n    at UserController.createUser (/server/server/controllers/user.controller.js:16:23)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async /server/server/routers/user.js:12:18","timestamp":"2021-09-14T15:10:26.642Z"}
{"message":"user already exists","statusCode":409,"level":"\u001b[31merror\u001b[39m","stack":"Error: user already exists\n    at new BaseError (/server/errors/baseError.js:8:11)\n    at new Conflict (/server/errors/errors.js:31:5)\n    at UserController.createUser (/server/server/controllers/user.controller.js:16:23)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async /server/server/routers/user.js:12:18","timestamp":"2021-09-14T15:12:51.362Z"}
{"level":"\u001b[31merror\u001b[39m","timestamp":"2021-09-14T15:12:51.364Z"}
{"message":"user already exists","statusCode":409,"level":"\u001b[31merror\u001b[39m","stack":"Error: user already exists\n    at new BaseError (/server/errors/baseError.js:8:11)\n    at new Conflict (/server/errors/errors.js:31:5)\n    at UserController.createUser (/server/server/controllers/user.controller.js:16:23)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async /server/server/routers/user.js:12:18","timestamp":"2021-09-14T15:13:27.158Z"}
{"level":"\u001b[31merror\u001b[39m","timestamp":"2021-09-14T15:13:27.160Z"}
{"message":"user already exists","statusCode":409,"level":"\u001b[31merror\u001b[39m","stack":"Error: user already exists\n    at new BaseError (/server/errors/baseError.js:8:11)\n    at new Conflict (/server/errors/errors.js:31:5)\n    at UserController.createUser (/server/server/controllers/user.controller.js:16:23)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async /server/server/routers/user.js:12:18","timestamp":"2021-09-14T15:14:09.209Z"}
{"level":"\u001b[31merror\u001b[39m","timestamp":"2021-09-14T15:14:09.212Z"}
{"message":"user already exists","statusCode":409,"level":"\u001b[31merror\u001b[39m","stack":"Error: user already exists\n    at new BaseError (/server/errors/baseError.js:8:11)\n    at new Conflict (/server/errors/errors.js:31:5)\n    at UserController.createUser (/server/server/controllers/user.controller.js:16:23)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async /server/server/routers/user.js:12:18","timestamp":"2021-09-14T15:15:21.799Z"}
{"level":"\u001b[31merror\u001b[39m","timestamp":"2021-09-14T15:15:21.802Z"}
{"message":"user already exists","statusCode":409,"level":"\u001b[31merror\u001b[39m","stack":"Error: user already exists\n    at new BaseError (/server/errors/baseError.js:8:11)\n    at new Conflict (/server/errors/errors.js:31:5)\n    at UserController.createUser (/server/server/controllers/user.controller.js:16:23)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async /server/server/routers/user.js:12:18","timestamp":"2021-09-14T15:15:40.929Z"}
{"level":"\u001b[31merror\u001b[39m","timestamp":"2021-09-14T15:15:40.931Z"}
{"message":"user already exists","statusCode":409,"level":"\u001b[31merror\u001b[39m","stack":"Error: user already exists\n    at new BaseError (/server/errors/baseError.js:8:11)\n    at new Conflict (/server/errors/errors.js:31:5)\n    at UserController.createUser (/server/server/controllers/user.controller.js:16:23)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async /server/server/routers/user.js:12:18","timestamp":"2021-09-14T15:17:25.558Z"}
{"level":"\u001b[31merror\u001b[39m","timestamp":"2021-09-14T15:17:25.559Z"}
{"message":"user already exists","statusCode":409,"level":"\u001b[31merror\u001b[39m","stack":"Error: user already exists\n    at new BaseError (/server/errors/baseError.js:8:11)\n    at new Conflict (/server/errors/errors.js:31:5)\n    at UserController.createUser (/server/server/controllers/user.controller.js:16:23)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async /server/server/routers/user.js:12:18","timestamp":"2021-09-14T15:17:48.535Z"}
{"message":"user already exists","statusCode":409,"level":"\u001b[31merror\u001b[39m","stack":"Error: user already exists\n    at new BaseError (/server/errors/baseError.js:8:11)\n    at new Conflict (/server/errors/errors.js:31:5)\n    at UserController.createUser (/server/server/controllers/user.controller.js:16:23)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async /server/server/routers/user.js:12:18","timestamp":"2021-09-14T15:18:01.968Z"}
{"message":"user already exists","statusCode":409,"level":"\u001b[31merror\u001b[39m","stack":"Error: user already exists\n    at new BaseError (/server/errors/baseError.js:8:11)\n    at new Conflict (/server/errors/errors.js:31:5)\n    at UserController.createUser (/server/server/controllers/user.controller.js:16:23)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async /server/server/routers/user.js:12:18","timestamp":"2021-09-14T15:18:27.703Z"}
{"message":"user already exists","statusCode":409,"level":"\u001b[31merror\u001b[39m","stack":"Error: user already exists\n    at new BaseError (/server/errors/baseError.js:8:11)\n    at new Conflict (/server/errors/errors.js:31:5)\n    at UserController.createUser (/server/server/controllers/user.controller.js:16:23)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async /server/server/routers/user.js:12:18","timestamp":"2021-09-14T15:25:19.452Z"}
{"level":"\u001b[31merror\u001b[39m","message":"this.adapter.getByID is not a function this.adapter.getByID is not a function","stack":"TypeError: this.adapter.getByID is not a function\n    at UserController.getByPk (/server/server/controllers/Controller.js:33:43)\n    at UserController.getUserByID (/server/server/controllers/user.controller.js:26:32)\n    at /server/server/routers/user.js:22:39\n    at Layer.handle [as handle_request] (/server/node_modules/express/lib/router/layer.js:95:5)\n    at next (/server/node_modules/express/lib/router/route.js:137:13)\n    at Route.dispatch (/server/node_modules/express/lib/router/route.js:112:3)\n    at Layer.handle [as handle_request] (/server/node_modules/express/lib/router/layer.js:95:5)\n    at /server/node_modules/express/lib/router/index.js:281:22\n    at param (/server/node_modules/express/lib/router/index.js:354:14)\n    at param (/server/node_modules/express/lib/router/index.js:365:14)","timestamp":"2021-09-14T15:30:12.540Z"}
{"level":"\u001b[31merror\u001b[39m","message":"this.adapter.getByID is not a function this.adapter.getByID is not a function","stack":"TypeError: this.adapter.getByID is not a function\n    at UserController.getByPk (/server/server/controllers/Controller.js:33:43)\n    at UserController.getUserByID (/server/server/controllers/user.controller.js:26:32)\n    at /server/server/routers/user.js:22:39\n    at Layer.handle [as handle_request] (/server/node_modules/express/lib/router/layer.js:95:5)\n    at next (/server/node_modules/express/lib/router/route.js:137:13)\n    at Route.dispatch (/server/node_modules/express/lib/router/route.js:112:3)\n    at Layer.handle [as handle_request] (/server/node_modules/express/lib/router/layer.js:95:5)\n    at /server/node_modules/express/lib/router/index.js:281:22\n    at param (/server/node_modules/express/lib/router/index.js:354:14)\n    at param (/server/node_modules/express/lib/router/index.js:365:14)","timestamp":"2021-09-14T15:30:12.545Z"}
{"level":"\u001b[31merror\u001b[39m","timestamp":"2021-09-14T15:30:12.547Z"}
{"level":"\u001b[31merror\u001b[39m","message":"Converting circular structure to JSON\n    --> starting at object with constructor 'Socket'\n    |     property '_writableState' -> object with constructor 'WritableState'\n    |     property 'afterWriteTickInfo' -> object with constructor 'Object'\n    --- property 'stream' closes the circle Converting circular structure to JSON\n    --> starting at object with constructor 'Socket'\n    |     property '_writableState' -> object with constructor 'WritableState'\n    |     property 'afterWriteTickInfo' -> object with constructor 'Object'\n    --- property 'stream' closes the circle","stack":"TypeError: Converting circular structure to JSON\n    --> starting at object with constructor 'Socket'\n    |     property '_writableState' -> object with constructor 'WritableState'\n    |     property 'afterWriteTickInfo' -> object with constructor 'Object'\n    --- property 'stream' closes the circle\n    at JSON.stringify (<anonymous>)\n    at Printf.template (/server/logger/logger-init.js:8:17)\n    at Printf.transform (/server/node_modules/logform/printf.js:11:26)\n    at Format.transform (/server/node_modules/logform/combine.js:20:24)\n    at DerivedLogger._transform (/server/node_modules/winston/lib/winston/logger.js:305:29)\n    at DerivedLogger.Transform._read (/server/node_modules/readable-stream/lib/_stream_transform.js:177:10)\n    at DerivedLogger.Transform._write (/server/node_modules/readable-stream/lib/_stream_transform.js:164:83)\n    at doWrite (/server/node_modules/readable-stream/lib/_stream_writable.js:409:139)\n    at writeOrBuffer (/server/node_modules/readable-stream/lib/_stream_writable.js:398:5)\n    at DerivedLogger.Writable.write (/server/node_modules/readable-stream/lib/_stream_writable.js:307:11)","timestamp":"2021-09-14T15:37:22.462Z"}
{"level":"\u001b[31merror\u001b[39m","message":"Converting circular structure to JSON\n    --> starting at object with constructor 'Socket'\n    |     property '_writableState' -> object with constructor 'WritableState'\n    |     property 'afterWriteTickInfo' -> object with constructor 'Object'\n    --- property 'stream' closes the circle Converting circular structure to JSON\n    --> starting at object with constructor 'Socket'\n    |     property '_writableState' -> object with constructor 'WritableState'\n    |     property 'afterWriteTickInfo' -> object with constructor 'Object'\n    --- property 'stream' closes the circle","stack":"TypeError: Converting circular structure to JSON\n    --> starting at object with constructor 'Socket'\n    |     property '_writableState' -> object with constructor 'WritableState'\n    |     property 'afterWriteTickInfo' -> object with constructor 'Object'\n    --- property 'stream' closes the circle\n    at JSON.stringify (<anonymous>)\n    at Printf.template (/server/logger/logger-init.js:8:17)\n    at Printf.transform (/server/node_modules/logform/printf.js:11:26)\n    at Format.transform (/server/node_modules/logform/combine.js:20:24)\n    at DerivedLogger._transform (/server/node_modules/winston/lib/winston/logger.js:305:29)\n    at DerivedLogger.Transform._read (/server/node_modules/readable-stream/lib/_stream_transform.js:177:10)\n    at DerivedLogger.Transform._write (/server/node_modules/readable-stream/lib/_stream_transform.js:164:83)\n    at doWrite (/server/node_modules/readable-stream/lib/_stream_writable.js:409:139)\n    at writeOrBuffer (/server/node_modules/readable-stream/lib/_stream_writable.js:398:5)\n    at DerivedLogger.Writable.write (/server/node_modules/readable-stream/lib/_stream_writable.js:307:11)","timestamp":"2021-09-14T15:38:12.331Z"}
{"message":"user already exists","statusCode":409,"level":"\u001b[31merror\u001b[39m","stack":"Error: user already exists\n    at new BaseError (/server/errors/baseError.js:8:11)\n    at new Conflict (/server/errors/errors.js:31:5)\n    at UserController.createUser (/server/server/controllers/user.controller.js:17:23)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async /server/server/routers/user.js:12:18","timestamp":"2021-09-14T15:42:40.954Z"}
{"message":"User not found","statusCode":404,"level":"\u001b[31merror\u001b[39m","stack":"Error: User not found\n    at new BaseError (/server/errors/baseError.js:8:11)\n    at new NotFound (/server/errors/errors.js:25:5)\n    at UserController.getUserByID (/server/server/controllers/user.controller.js:28:24)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async /server/server/routers/user.js:22:18","timestamp":"2021-09-14T15:59:55.987Z"}
{"level":"\u001b[31merror\u001b[39m","timestamp":"2021-09-14T16:34:57.465Z"}
{"name":"SequelizeAccessDeniedError","parent":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlState":"28000","sqlMessage":"Access denied for user 'root'@'172.23.0.4' (using password: YES)"},"original":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlState":"28000","sqlMessage":"Access denied for user 'root'@'172.23.0.4' (using password: YES)"},"level":"\u001b[31merror\u001b[39m","message":"Unable to connect to the database: Access denied for user 'root'@'172.23.0.4' (using password: YES)","stack":"SequelizeAccessDeniedError: Access denied for user 'root'@'172.23.0.4' (using password: YES)\n    at ConnectionManager.connect (/server/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:118:17)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async ConnectionManager._connect (/server/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:318:24)\n    at async /server/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:250:32\n    at async ConnectionManager.getConnection (/server/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:280:7)\n    at async /server/node_modules/sequelize/lib/sequelize.js:613:26\n    at async Sequelize.authenticate (/server/node_modules/sequelize/lib/sequelize.js:867:5)","timestamp":"2021-10-04T15:19:40.713Z"}
{"name":"SequelizeAccessDeniedError","parent":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlState":"28000","sqlMessage":"Access denied for user 'root'@'172.23.0.4' (using password: YES)"},"original":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlState":"28000","sqlMessage":"Access denied for user 'root'@'172.23.0.4' (using password: YES)"},"level":"\u001b[31merror\u001b[39m","message":"Unable to connect to the database: Access denied for user 'root'@'172.23.0.4' (using password: YES)","stack":"SequelizeAccessDeniedError: Access denied for user 'root'@'172.23.0.4' (using password: YES)\n    at ConnectionManager.connect (/server/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:118:17)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async ConnectionManager._connect (/server/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:318:24)\n    at async /server/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:250:32\n    at async ConnectionManager.getConnection (/server/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:280:7)\n    at async /server/node_modules/sequelize/lib/sequelize.js:613:26\n    at async Sequelize.authenticate (/server/node_modules/sequelize/lib/sequelize.js:867:5)","timestamp":"2021-10-04T15:22:15.120Z"}
{"name":"SequelizeAccessDeniedError","parent":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlState":"28000","sqlMessage":"Access denied for user 'root'@'172.24.0.4' (using password: YES)"},"original":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlState":"28000","sqlMessage":"Access denied for user 'root'@'172.24.0.4' (using password: YES)"},"level":"\u001b[31merror\u001b[39m","message":"Unable to connect to the database: Access denied for user 'root'@'172.24.0.4' (using password: YES)","stack":"SequelizeAccessDeniedError: Access denied for user 'root'@'172.24.0.4' (using password: YES)\n    at ConnectionManager.connect (/server/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:118:17)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async ConnectionManager._connect (/server/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:318:24)\n    at async /server/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:250:32\n    at async ConnectionManager.getConnection (/server/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:280:7)\n    at async /server/node_modules/sequelize/lib/sequelize.js:613:26\n    at async Sequelize.authenticate (/server/node_modules/sequelize/lib/sequelize.js:867:5)","timestamp":"2021-10-04T15:24:46.204Z"}
{"name":"SequelizeConnectionError","parent":{"code":"ER_BAD_DB_ERROR","errno":1049,"sqlState":"42000","sqlMessage":"Unknown database 'elmenus_db'"},"original":{"code":"ER_BAD_DB_ERROR","errno":1049,"sqlState":"42000","sqlMessage":"Unknown database 'elmenus_db'"},"level":"\u001b[31merror\u001b[39m","message":"Unable to connect to the database: Unknown database 'elmenus_db'","stack":"SequelizeConnectionError: Unknown database 'elmenus_db'\n    at ConnectionManager.connect (/server/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:126:17)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async ConnectionManager._connect (/server/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:318:24)\n    at async /server/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:250:32\n    at async ConnectionManager.getConnection (/server/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:280:7)\n    at async /server/node_modules/sequelize/lib/sequelize.js:613:26\n    at async Sequelize.authenticate (/server/node_modules/sequelize/lib/sequelize.js:867:5)","timestamp":"2021-10-04T15:27:47.334Z"}
{"name":"SequelizeConnectionError","parent":{"code":"ER_BAD_DB_ERROR","errno":1049,"sqlState":"42000","sqlMessage":"Unknown database 'elmenus_db'"},"original":{"code":"ER_BAD_DB_ERROR","errno":1049,"sqlState":"42000","sqlMessage":"Unknown database 'elmenus_db'"},"level":"\u001b[31merror\u001b[39m","message":"Unable to connect to the database: Unknown database 'elmenus_db'","stack":"SequelizeConnectionError: Unknown database 'elmenus_db'\n    at ConnectionManager.connect (/server/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:126:17)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async ConnectionManager._connect (/server/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:318:24)\n    at async /server/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:250:32\n    at async ConnectionManager.getConnection (/server/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:280:7)\n    at async /server/node_modules/sequelize/lib/sequelize.js:613:26\n    at async Sequelize.authenticate (/server/node_modules/sequelize/lib/sequelize.js:867:5)","timestamp":"2021-10-04T15:31:38.936Z"}
{"name":"SequelizeConnectionError","parent":{"code":"ER_BAD_DB_ERROR","errno":1049,"sqlState":"42000","sqlMessage":"Unknown database 'elmenus_db'"},"original":{"code":"ER_BAD_DB_ERROR","errno":1049,"sqlState":"42000","sqlMessage":"Unknown database 'elmenus_db'"},"level":"\u001b[31merror\u001b[39m","message":"Unable to connect to the database: Unknown database 'elmenus_db'","stack":"SequelizeConnectionError: Unknown database 'elmenus_db'\n    at ConnectionManager.connect (/server/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:126:17)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async ConnectionManager._connect (/server/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:318:24)\n    at async /server/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:250:32\n    at async ConnectionManager.getConnection (/server/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:280:7)\n    at async /server/node_modules/sequelize/lib/sequelize.js:613:26\n    at async Sequelize.authenticate (/server/node_modules/sequelize/lib/sequelize.js:867:5)","timestamp":"2021-10-04T15:34:34.603Z"}
{"level":"\u001b[31merror\u001b[39m","message":"Validation error: \"email\" is required, \"password\" is required","timestamp":"2021-10-04T19:45:19.704Z"}
{"level":"\u001b[31merror\u001b[39m","message":"Validation error: \"email\" is required, \"password\" is required","timestamp":"2021-10-04T19:46:47.164Z"}
{"level":"\u001b[31merror\u001b[39m","message":"Validation error: \"email\" is required, \"password\" is required","timestamp":"2021-10-04T19:47:51.795Z"}
{"message":"user already exists","statusCode":409,"level":"\u001b[31merror\u001b[39m","stack":"Error: user already exists\n    at new BaseError (/server/errors/baseError.js:8:11)\n    at new Conflict (/server/errors/errors.js:31:5)\n    at UserController.createUser (/server/server/controllers/user.controller.js:16:23)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async /server/server/routers/user.js:12:18","timestamp":"2021-10-04T19:58:21.262Z"}
{"name":"SequelizeValidationError","errors":[{"message":"user.id cannot be null","type":"notNull Violation","path":"id","value":null,"origin":"CORE","instance":{"id":null,"updatedAt":"2021-10-04T19:58:29.682Z","createdAt":"2021-10-04T19:58:29.682Z"},"validatorKey":"is_null","validatorName":null,"validatorArgs":[]}],"level":"\u001b[31merror\u001b[39m","message":"notNull Violation: user.id cannot be null notNull Violation: user.id cannot be null","stack":"SequelizeValidationError: notNull Violation: user.id cannot be null\n    at InstanceValidator._validate (/server/node_modules/sequelize/lib/instance-validator.js:78:13)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async InstanceValidator._validateAndRunHooks (/server/node_modules/sequelize/lib/instance-validator.js:111:7)\n    at async InstanceValidator.validate (/server/node_modules/sequelize/lib/instance-validator.js:93:12)\n    at async model.save (/server/node_modules/sequelize/lib/model.js:3890:7)\n    at async Function.create (/server/node_modules/sequelize/lib/model.js:2207:12)\n    at async UserAdapter.create (/server/server/adapters/mysql_database/BaseAdapter.js:18:24)\n    at async UserAdapter.create (/server/server/adapters/mysql_database/user.adapter.js:13:20)\n    at async UserController.create (/server/server/controllers/Controller.js:23:24)\n    at async UserController.createUser (/server/server/controllers/user.controller.js:17:14)","timestamp":"2021-10-04T19:58:29.686Z"}
{"name":"SequelizeValidationError","errors":[{"message":"user.id cannot be null","type":"notNull Violation","path":"id","value":null,"origin":"CORE","instance":{"id":null,"updatedAt":"2021-10-04T19:58:29.682Z","createdAt":"2021-10-04T19:58:29.682Z"},"validatorKey":"is_null","validatorName":null,"validatorArgs":[]}],"level":"\u001b[31merror\u001b[39m","message":"notNull Violation: user.id cannot be null notNull Violation: user.id cannot be null","stack":"SequelizeValidationError: notNull Violation: user.id cannot be null\n    at InstanceValidator._validate (/server/node_modules/sequelize/lib/instance-validator.js:78:13)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async InstanceValidator._validateAndRunHooks (/server/node_modules/sequelize/lib/instance-validator.js:111:7)\n    at async InstanceValidator.validate (/server/node_modules/sequelize/lib/instance-validator.js:93:12)\n    at async model.save (/server/node_modules/sequelize/lib/model.js:3890:7)\n    at async Function.create (/server/node_modules/sequelize/lib/model.js:2207:12)\n    at async UserAdapter.create (/server/server/adapters/mysql_database/BaseAdapter.js:18:24)\n    at async UserAdapter.create (/server/server/adapters/mysql_database/user.adapter.js:13:20)\n    at async UserController.create (/server/server/controllers/Controller.js:23:24)\n    at async UserController.createUser (/server/server/controllers/user.controller.js:17:14)","timestamp":"2021-10-04T19:58:29.687Z"}
{"name":"SequelizeValidationError","errors":[{"message":"user.id cannot be null","type":"notNull Violation","path":"id","value":null,"origin":"CORE","instance":{"id":null,"updatedAt":"2021-10-04T19:58:29.682Z","createdAt":"2021-10-04T19:58:29.682Z"},"validatorKey":"is_null","validatorName":null,"validatorArgs":[]}],"level":"\u001b[31merror\u001b[39m","message":"notNull Violation: user.id cannot be null notNull Violation: user.id cannot be null","stack":"SequelizeValidationError: notNull Violation: user.id cannot be null\n    at InstanceValidator._validate (/server/node_modules/sequelize/lib/instance-validator.js:78:13)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async InstanceValidator._validateAndRunHooks (/server/node_modules/sequelize/lib/instance-validator.js:111:7)\n    at async InstanceValidator.validate (/server/node_modules/sequelize/lib/instance-validator.js:93:12)\n    at async model.save (/server/node_modules/sequelize/lib/model.js:3890:7)\n    at async Function.create (/server/node_modules/sequelize/lib/model.js:2207:12)\n    at async UserAdapter.create (/server/server/adapters/mysql_database/BaseAdapter.js:18:24)\n    at async UserAdapter.create (/server/server/adapters/mysql_database/user.adapter.js:13:20)\n    at async UserController.create (/server/server/controllers/Controller.js:23:24)\n    at async UserController.createUser (/server/server/controllers/user.controller.js:17:14)","timestamp":"2021-10-04T19:58:29.687Z"}
{"name":"SequelizeValidationError","errors":[{"message":"user.id cannot be null","type":"notNull Violation","path":"id","value":null,"origin":"CORE","instance":{"id":null,"updatedAt":"2021-10-04T19:58:29.682Z","createdAt":"2021-10-04T19:58:29.682Z"},"validatorKey":"is_null","validatorName":null,"validatorArgs":[]}],"level":"\u001b[31merror\u001b[39m","message":"notNull Violation: user.id cannot be null notNull Violation: user.id cannot be null","stack":"SequelizeValidationError: notNull Violation: user.id cannot be null\n    at InstanceValidator._validate (/server/node_modules/sequelize/lib/instance-validator.js:78:13)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async InstanceValidator._validateAndRunHooks (/server/node_modules/sequelize/lib/instance-validator.js:111:7)\n    at async InstanceValidator.validate (/server/node_modules/sequelize/lib/instance-validator.js:93:12)\n    at async model.save (/server/node_modules/sequelize/lib/model.js:3890:7)\n    at async Function.create (/server/node_modules/sequelize/lib/model.js:2207:12)\n    at async UserAdapter.create (/server/server/adapters/mysql_database/BaseAdapter.js:18:24)\n    at async UserAdapter.create (/server/server/adapters/mysql_database/user.adapter.js:13:20)\n    at async UserController.create (/server/server/controllers/Controller.js:23:24)\n    at async UserController.createUser (/server/server/controllers/user.controller.js:17:14)","timestamp":"2021-10-04T19:58:29.688Z"}
{"name":"SequelizeValidationError","errors":[{"message":"user.id cannot be null","type":"notNull Violation","path":"id","value":null,"origin":"CORE","instance":{"id":null,"updatedAt":"2021-10-04T19:58:29.682Z","createdAt":"2021-10-04T19:58:29.682Z"},"validatorKey":"is_null","validatorName":null,"validatorArgs":[]}],"level":"\u001b[31merror\u001b[39m","timestamp":"2021-10-04T19:58:29.689Z"}
{"message":"user already exists","statusCode":409,"level":"\u001b[31merror\u001b[39m","stack":"Error: user already exists\n    at new BaseError (/server/errors/baseError.js:8:11)\n    at new Conflict (/server/errors/errors.js:31:5)\n    at UserController.createUser (/server/server/controllers/user.controller.js:16:23)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async /server/server/routers/user.js:12:18","timestamp":"2021-10-04T20:06:22.312Z"}
{"level":"\u001b[31merror\u001b[39m","timestamp":"2021-10-05T20:21:54.892Z"}
{"message":"item not found","statusCode":404,"level":"\u001b[31merror\u001b[39m","stack":"Error: item not found\n    at new BaseError (/server/errors/baseError.js:8:11)\n    at new NotFound (/server/errors/errors.js:25:5)\n    at ItemController.getItemByID (/server/server/controllers/item.controller.js:29:24)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async /server/server/routers/item.js:23:18","timestamp":"2021-10-05T20:34:18.870Z"}
{"message":"Invalid parameters update","statusCode":422,"level":"\u001b[31merror\u001b[39m","stack":"Error: Invalid parameters update\n    at new BaseError (/server/errors/baseError.js:8:11)\n    at new UnprocessableEntity (/server/errors/errors.js:37:5)\n    at ItemController.updateItem (/server/server/controllers/item.controller.js:43:15)\n    at /server/server/routers/item.js:34:26\n    at Layer.handle [as handle_request] (/server/node_modules/express/lib/router/layer.js:95:5)\n    at next (/server/node_modules/express/lib/router/route.js:137:13)\n    at validateRequest (/server/server/schemas/validateRequest.js:16:10)\n    at itemUpdateRequestSchema (/server/server/schemas/item.js:18:3)\n    at Layer.handle [as handle_request] (/server/node_modules/express/lib/router/layer.js:95:5)\n    at next (/server/node_modules/express/lib/router/route.js:137:13)","timestamp":"2021-10-05T21:04:15.934Z"}
